### PR TITLE
Adding all NYU Abu Dhabi Faculty & updates to faculty who have moved to NYU Abu Dhabi

### PR DESCRIPTION
**Pull request by bharathprabakaran**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
On a spot check, it appears all of these are ECE faculty, not CS (https://nyuad.nyu.edu/en/academics/divisions/science/faculty.html?_charset_=UTF-8&program=computer-science-major&affiliation=&keywords=). Please clarify how they meet the inclusion criteria.

**Comment by bharathprabakaran** [comment]
All the full-time tenure-track CS faculty from the link that you have shared are already present in the changes requested. 

The requested changes also include all full-time tenure-track faculty in Electrical (https://nyuad.nyu.edu/en/academics/divisions/engineering/faculty.html?_charset_=UTF-8&program=electrical-engineering-major&affiliation=NYU+Abu+Dhabi&keywords=) and Computer Engineering (https://nyuad.nyu.edu/en/academics/divisions/engineering/faculty.html?_charset_=UTF-8&program=computer-engineering-major&affiliation=NYU+Abu+Dhabi&keywords=) departments who can solely supervise PhD students in a domain of CS.

**Comment by emeryberger** [comment]
Only people who can solely supervise a PhD _in Computer Science_ are eligible. That means, in the department that grants a degree in computer science, not EE or ECE. This often but not always requires a cross-appointment (courtesy or adjunct).

**Comment by niniack** [comment]
Hello! I'm looking to reopen this conversation! 

How does NYU Tandon's "Computer Science and Engineering" (CSE) fit into this framework? Here's the [NYU Tandon page](https://engineering.nyu.edu/academics/departments/computer-science-and-engineering) for the major. 

The closest thing to pure "Computer Science" at Tandon is CSE. [Here's a full list](https://engineering.nyu.edu/academics/departments) of Tandon departments. As of right now, NYU Abu Dhabi CSE faculty supervise PhDs exclusively through Tandon. In other words, _all_ CSE PhD students that work with NYU Abu Dhabi faculty are _actually_ enrolled as Tandon CSE students.

I am assuming that csrankings.org recognizes CSE at Tandon. I say that because I'm seeing certain professors (e.g. [here](https://engineering.nyu.edu/faculty/ramesh-karri)) that I know as Tandon CSE professors, and have the same PhD supervision rights as the NYU Abu Dhabi faculty, showing up under NYU on csrankings.org.
 
Operating under this assumption, in terms of inclusion criteria, would it be sufficient to show that the professors in this commit can solely supervise dissertation credits in CSE at Tandon? If so, here's some documentation:

Azza Abouzied
image

Anthony Tzes
image

Christina Popper
image

Hoda AlKhzaimi
image

Michail Maniatakos
image

Muhammad Shafique
image

Yi Fang
image

I grabbed these screenshots off of [NYU's public course search page](https://albert.nyu.edu/albert_index.html). I admit that this documentation is not the easiest to obtain, given the pesky captcha. Still, I'd like to put forth that technically this information is available on a public page, accessible to anyone, no login required. If you believe there is something better I can provide, I would be more than happy to do so!

In addition, some of the faculty in the commit are not part of our Engineering department! Rather they are part of the "Science" department. They supervise PhDs through NYU's Courant Institute (their affiliation is mentioned explicitly in the links below), so the documentation there is a bit more straightforward. 

[Saurabh Ray](https://nyuad.nyu.edu/en/academics/divisions/science/faculty/saurabh-ray.html)
[Nizar Habash](https://nyuad.nyu.edu/en/academics/divisions/science/faculty/nizar-habash.html)
[Yasir Zaki](https://nyuad.nyu.edu/en/academics/divisions/science/faculty/yasir-zaki.html)
[Djellel Difallah](https://nyuad.nyu.edu/en/academics/divisions/science/faculty/djellel-difallah.html)
You are right to correct the OP in that not all of the faculty in the commit can supervise CS PhDs. I have provided documentation for the ones in the commit that can. Of course, there are other professors that meet the inclusion criteria that just were not captured in the commit to begin with, but that's a second step. Either way, I want to open up this conversation to get NYUAD on csrankings.org and this commit seems like a good starting point!

Thanks for your time!

**Pull request closed without merging**
