### PR TITLE
Tuebingen

### PR DESCRIPTION
**Pull request by j-cb**
Added the following faculty of the University of Tübingen:

Jakob H. Macke,University of Tübingen,https://uni-tuebingen.de/en/research/core-research/cluster-of-excellence-machine-learning/research/research/cluster-research-groups/professorships/machine-learning-in-science/ ,FKOqtF8AAAAJ
Zhaoping Li,University of Tübingen,https://webdav.tuebingen.mpg.de/u/zli/bio.html ,V3sgCS0AAAAJ
Philipp Berens,University of Tübingen,http://www.eye-tuebingen.de/berens/ ,lPQLk3QAAAAJ
Reinhard Kahle,University of Tübingen,https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/interfaculty-facilities/philosophy-and-history-of-science/#c840039 ,NOSCHOLARPAGE
Martin A. Giese,University of Tübingen,http://www.compsens.uni-tuebingen.de/compsens/index.php/people?view=member&task=show&id=1 ,ebo0Qn4AAAAJ
Stephan Ossowski,University of Tübingen,http://www.medgen-tuebingen.de/en/f-computational-genomics-group-leader.html ,imRxrJ4AAAAJ
Bettina Rolke,University of Tübingen,https://fit.uni-tuebingen.de/Portfolio/Details?id=495 ,NOSCHOLARPAGE
Manfred Claassen,University of Tübingen,https://www.medizin.uni-tuebingen.de/de/das-klinikum/mitarbeiter/profil/2147 ,NOSCHOLARPAGE

Removed entry with former institution:

_Zhaoping Li,University College London,http://www0.cs.ucl.ac.uk/staff/Zhaoping.Li,V3sgCS0AAAAJ_

In earlier commits but already in the current main gh-pages branch:

~~Michael Kaufmann 0001,University of Tübingen,http://algo.inf.uni-tuebingen.de/?site=mitarbeiter/michaelkaufmann/index ,FTx_BNsAAAAJ~~
~~Klaus-Jörn Lange,University of Tübingen,https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/computer-science/lehrstuehle/theoretical-computer-science/home/ ,NOSCHOLARPAGE~~
~~Michael Menth,University of Tübingen,https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/computer-science/lehrstuehle/communication-networks/staff/menth/ ,nIb1MnoAAAAJ~~
~~Volker H. Franz,University of Tübingen,http://www.ecogsci.cs.uni-tuebingen.de/team/volker-franz/ ,g_ByVUYAAAAJ~~

Status unclear, to be added in separate pull request:

~~Britta Dorn,University of Tübingen,https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/computer-science/lehrstuehle/mathematische-strukturen/home/ ,0hGJH9UAAAAJ~~

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by Ben5000** [comment]
All links evidencing the the webpages of faculty added (excluding two), are *broken*!

**Comment by j-cb** [comment]
> All links evidencing the the webpages of faculty added (excluding two), are _broken_!

This only concerned the pull request comment above, right? There I had pasted the added lines of the csv, and github parsed the comma separator and the following scholar ID as part of the hyperlink. I just edited the comment so there are spaces before these commas; now the links are clickable.

**Comment by Ben5000** [comment]
The links do work now, thanks. But the people added are mostly not from CS. Some are from philosophy, some biology, some cognitive science, and some are Junior Professor, meaning something equivalent to a postdoc.

**Comment by j-cb** [comment]
All of the added faculty can advise PhD students in CS and have permanent positions.
They are all listed at https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/computer-science/research-groups/ .
Those marked with "coopted" have another home department, but can advise CS PhDs, which is allowed by the CSrankings inclusion criteria.

The Junior Professor position includes the ability to advise PhD students, for example Britta Dorn currently supervises Janosch Döcker (see https://uni-tuebingen.de/en/faculties/faculty-of-science/departments/computer-science/lehrstuehle/mathematische-strukturen/home/team/).

In the latest commit, I removed the sadly recently deceased Wolfgang Rosenstiel and added Manfred Claassen, who joined with a professorship on Clinical bioinformatics & Machine learning (also coopted).

If there are still people whose status is unclear, it would make sense to discuss them individually.

**Comment by Ben5000** [comment]
My understanding is that a Juniordozentin is *not* a permanent position, but a fixed-term (e.g., 5 years) hence although may be able to supervise students, is not eligible for inclusion.

**Comment by j-cb** [comment]
For Jun.-Doz., the situations can be different (also regarding tenure track) and the information is sometimes not publicly available.
Britta Dorn (the only Jun.-Doz. that was in the pull request) has recently got a permanent position but is now on parental leave. Thus we took her out for the moment and then will add her separately once the information on the department website is updated.

**Comment by emeryberger** [comment]
Please pull again to resolve conflicts with `csrankings.csv`.

**Comment by j-cb** [comment]
Done, and also removed some additions that would have been duplicates.

By the way, sorting the `csrankings.csv` file correctly took me some time to figure out, and for me the most convenient way to do it was by:
 `export LC_ALL=C`
`(head -n 1 csrankings.csv && tail -n +2 csrankings.csv | sort -k1 -t,) > csrankings_sorted.csv`
This might be a good addition to CONTRIBUTING.md, but I didn't include it in this pull request yet.

**Comment by emeryberger** [comment]
FWIW, if you invoke `make clean-csrankings` it does a bunch of things, including sorting `csrankings.csv`. I do this after every update.

**Comment by emeryberger** [comment]
This diff is really too large for me to audit. Please just open another PR and add these new faculty -- thanks.

**Pull request closed without merging**
