### PR TITLE
add myself: Nanyun (Violet) Peng from usc isi. I'm not a tenure-track…

### PR DESCRIPTION
**Pull request by VioletPeng**
… cs faculty, but can independently advise cs phd students. I have established an NLP group. Please refer to my group website: https://violetpeng.github.io/group.html. I am anticipating recruiting 2-3 more cs phd students this year. I think I meet the criteria and get on this list can facilitate my recruitment. Thank you!

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - tenure track faculty are not currently eligible for inclusion.

**Comment by VioletPeng** [comment]
Hello, I'm not a tenure-track. I specified this in the title.
I'm following this criterion: Faculty not in a CS department or similar who can advise PhD students in CS *can be* included regardless of their home department. 
I'm involved in the whole PhD hiring process of the CS department.
Besides, I consider myself the same situation as Eduard Hovy who is included in your list.
If it ever helps, I turned down several US top 30 cs tenure-track positions to join my current job. I think I'm well qualified.

**Comment by emeryberger** [comment]
Hi Violet,

Yes, I saw that. Thanks for the clarification. I have corrected the anomaly you mention. This is meant to be a uniform standard across departments around the world; the inclusion criteria have always been limited to tenure track faculty. This may be revisited in the future but that is part of the current criteria.

**Comment by VioletPeng** [comment]
Hi Emery,

Can you explain why the criteria makes sense if the goal of your website, as specified on your website, is "This ranking is designed to identify institutions and faculty actively engaged in research across a number of areas of computer science, based on the number of publications by faculty that have appeared at the most selective conferences in each area of computer science"?

**Comment by VioletPeng** [comment]
Also, could you please explain why Eduard Hovy as a non-tenure-track professor is eligible for the list?

**Comment by emeryberger** [comment]
Hovy has been removed.

Research faculty have not been included for a variety of reasons: (1) it could serve as an incentive to reduce tenure-track appointments, which are more expensive; (2) research faculty are "free" for institutions (soft money funded) and this could be gamed to improve rankings at little cost by hiring (again, at zero cost) a large number of research faculty; (3) tenure-track faculty are "permanent" and thus in principle more likely to remain affiliated with the institution for the duration of a PhD. This decision could always be revisited, but it is the current standard.

**Comment by VioletPeng** [comment]
One thing that makes more sense to me and will basically eliminate most of your concerns about including research faculty is to reduce the population effect of your ranking list. So that the ranking won't increase purely by adding more faculty to a school.
Also, all your concerns about research faculty also apply to the tenure-track faculty in other departments that have a courtesy appointment in cs (who are eligible from my understanding of your criteria).
In general, I feel there's some discrimination against research faculty here going on. which is very disappointing.

**Comment by VioletPeng** [comment]
Also, I don't think tenure-track is "permanent" at all. There are only real differences between tenured and pre-tenure.

**Pull request closed without merging**
