### PR TITLE
Add faculty members from Thai-German Graduate School at KMUTNB

### PR DESCRIPTION
**Pull request by rausavar**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by rausavar** [comment]
I have resolved the conflict from recent updates and added every faculty who can solely advise CS students (from the CS department).

**Comment by rausavar** [comment]
Dear @emeryberger,

Could you please explain why this pull request has been ignored for months and let me know how can I resolve your issue of adding faculty in my department (TGGS) to the database? I have included all tenure-track faculty at TGGS who can advise CS students to this pull request. 

I understand that the university is unknown and it might not be clear to you if our department falls within CSranking inclusion policy or not. If you would like me to go an extra step and see additional supporting documents from our dean, please feels free to let me know. 

A few of our professors including myself already have a handful of top-tier publications that are included in the ranking (ISCA/MICRO/ASPLOS/HPCA/SIGMOD/VLDB/ECCV/DAC/SIGMETRICS), and the inclusion would definitely help prospective students in the Southeast Asia region to search for experts in each field and help each of us to expand the community in these extremely underrepresented regions.

Regards,

**Comment by emeryberger** [comment]
Hi. I was on sabbatical all last year, and I am only now catching up on a backlog since this summer. Please rebase your PR to resolve conflicts -- and please change the name to KMUTNB (the current name is too long). I remain unable to connect to your institution's home page, so I have no way of verifying any information, which is a problem...

**Comment by rausavar** [comment]
Dear @emeryberger 
Thank you very much for you reply. I have changed the institution name to KMUTNB.

The institution home page is at: https://kmutnb.ac.th/
The info on my department from KMUTNB's website is at: https://kmutnb.ac.th/faculty-and-agencies/bangkok/the-sirindhorn-tggs.aspx
My department home page is at: https://tggs.kmutnb.ac.th/

**Pull request merged**
