### PR TITLE
Unl branch-update Added Researcher

### PR DESCRIPTION
**Pull request by lcaires**

### CODE REVIEW

**Comment by emeryberger** [comment]
You need to remove all spaces after the university name.

**Comment by emeryberger** [comment]
Great - please resolve all conflicts and I will merge.

**Comment by emeryberger** [comment]
Ping @lcaires

**Comment by emeryberger** [comment]
Sorry, new conflicts. Please update again.

**Comment by emeryberger** [comment]
Bump @lcaires

**Comment by lcaires** [comment]
Thanks !

**Pull request merged**
