### PR TITLE
Added University of Guelph

### PR DESCRIPTION
**Pull request by quettabit**

### CODE REVIEW

**Comment by quettabit** [comment]
Cross-checked with dblp entries.

**Comment by emeryberger** [comment]
Several of these faculty members are not in computer science. Please remove and re-submit.
e.g., https://www.uoguelph.ca/engineering/content/faculty/medhat-moussa

(See https://www.uoguelph.ca/computing/people)

**Comment by quettabit** [comment]
@emeryberger yeah they were in computer engineering ... but few like Medhat, Taylor are working on areas like ML, Vision, Robotics etc., So thought it would be useful

**Comment by emeryberger** [comment]
See https://github.com/emeryberger/CSrankings/blob/gh-pages/docs/CONTRIBUTING.md

**Comment by quettabit** [comment]
Sure ... "Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department."  - Added them based on this, assuming the students to be PhD in CS. Rechecked now. No, they are not.

**Comment by quettabit** [comment]
Will remove them now and commit.

**Pull request merged**
