### PR TITLE
Removed faculty from BITS Pilani and IIT Roorkee who had incorrect DBLP entry

### PR DESCRIPTION
**Pull request by dishuk13**
This is the list of faculty which were removed. 
* Arun Chauhan, BITS Pilani
* Vishal Gupta,  BITS Pilani
* Sandeep Kumar, IIT Roorkee

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you amend your PR with the corrected DBLP entries? Thanks.

**Comment by dishuk13** [comment]
The thing is that either they don't have DBLP entries or their publications are mixed with another person of the same name.

**Comment by emeryberger** [comment]
No DBLP entries = no problem (since no papers will appear).

Please let me know which ones need a disambiguation entry. The DBLP folks have been pretty good about fixing this, especially when you can identify publications belonging to the "right" person.

**Comment by emeryberger** [comment]
@divyanshshukla13

**Comment by emeryberger** [comment]
Closing until this is addressed.

**Comment by dishuk13** [comment]
@emeryberger 
[Arun Chauhan](http://www.bits-pilani.ac.in/pilani/arunchauhan/Publications)  [DBLP](http://dblp.uni-trier.de/pers/hd/c/Chauhan:Arun)
His DBLP entry is mixed with somebody else's.

[Vishal Gupta](http://universe.bits-pilani.ac.in/pilani/vishalgupta/Publications)
He doesn't have a DBLP entry.

[Sandeep Kumar Garg](http://www.iitr.ac.in/departments/CSE/pages/People+Faculty+sgargfec.html) 
I couldn't find his publications anywhere.

**Comment by emeryberger** [comment]
OK, I have asked DBLP to create a disambiguation entry for Chauhan. Thanks.

**Pull request merged**
