### PR TITLE
Added my information (Hamzeh Khazaei) to the database.

### PR DESCRIPTION
**Pull request by hamzehkhazaei**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
The diff is the whole `csrankings.csv` file, possibly because of a line ending issue. Please submit a diff that is just you. Alternatively, paste in the line in a comment here.

**Comment by fycus-tree** [comment]
Is ECE, not CS faculty
https://www.ualberta.ca/computing-science/faculty-and-staff/faculty

**Comment by emeryberger** [comment]
Good catch, @fycus-tree - thanks. I went to @hamzehkhazaei's home page, and there's no indication there of a secondary appointment. Please read the inclusion criteria.

**Comment by hamzehkhazaei** [comment]
Hello Guys, 
So, did you merge my info or not? 
I am a faculty member in ECE in software engineering and intelligent systems; I am not part of CS department but I supervise students in the area of performance engineering, software engineering and cloud computing.

Thanks,
Hamzeh

**Comment by emeryberger** [comment]
Hi. You do not meet the inclusion criteria. This is true for ECE folks who are not cross-appointed in their institution's CS department.

> * Make sure that any faculty you add meet the inclusion
  criteria. Eligible faculty include only full-time, tenure-track
  faculty members on a given campus who can advise PhD students in
  Computer Science. Faculty not in a CS department or similar who can
  advise PhD students in CS can be included regardless of their home
  department.

**Comment by hamzehkhazaei** [comment]
I can advise PhD students in CS. @emeryberger @fycus-tree;
In fact right now, 3 of my student are co supervised with CS department.

**Comment by hamzehkhazaei** [comment]
I have this condition: 
" Faculty not in a CS department or similar who can
  advise PhD students in CS can be included regardless of their home
  department."

**Comment by emeryberger** [comment]
Apologies for the lack of clarity: you need to be able to _solely_ supervise students for a PhD _in CS_.

**Pull request closed without merging**
