### PR TITLE
Update IIT Roorkee faculty

### PR DESCRIPTION
**Pull request by respel**

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you confirm this removal with some data? This faculty member's web page is still active: https://www.iitr.ac.in/departments/CSE/pages/People+Faculty+sgargfec.html

**Comment by respel** [comment]
The faculty member is still there but the DBLP handle doesn't correspond. Also he doesn't even seem to have a legit one. IMO, it is better to have missing info than info which is outrightly wrong.

**Comment by emeryberger** [comment]
Is your point that the DBLP entries include papers by other authors as well as this faculty member? This is a common problem that is best resolved by opening an issue for me to raise it with the DBLP folks. See, for example, https://github.com/emeryberger/CSrankings/issues/447.

**Comment by emeryberger** [comment]
If you'd be so kind, please open issues for all of these authors. Then I will merge your PRs and restore the faculty members after DBLP updates their entries. Thanks.

**Pull request merged**
