### PR TITLE
Adding TU Berlin data

### PR DESCRIPTION
**Pull request by jsalmodovar**
# Contributing to CSrankings

We have just uploaded data corresponding to the CS Faculty at TU Berlin.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please resolve conflicts and I will merge. Thanks.

**Comment by akunft** [comment]
Resolved the conflicts. Should be ready to merge now.

**Comment by emeryberger** [comment]
Sadly, no...

**Comment by akunft** [comment]
It did before the merged pull requests. Updated again.
While rebasing, I saw a duplicate in the file. Don't know if that is interesting.

`Xiaowei Yang,Duke University,https://users.cs.duke.edu/~xwy,cVTdh_sAAAAJ`

**Comment by emeryberger** [comment]
Thanks for the note (and the contribution!).

**Pull request merged**
