### PR TITLE
Adding full-time faculty from the IMDEA Software Institute

### PR DESCRIPTION
**Pull request by pierreganty**

### CODE REVIEW

**Comment by emeryberger** [comment]
AFAIK IMDEA is not a PhD degree-granting institution, correct?

**Comment by emeryberger** [comment]
If not, it is not eligible for inclusion in the rankings.

**Comment by pierreganty** [comment]
IMDEA does not grant degrees to PhD students. That is correct.
However, afaik we are in the exact same situation as the MPI-SWS which is included in the ranking.

**Comment by emeryberger** [comment]
That characterization of MPI-SWS is not accurate, as far as I can tell: PhD students have MPI supervisors.

https://www.mpi-sws.org/index.php?n=graduate#graduate-school

**Comment by pierreganty** [comment]
[Here](http://software.imdea.org/people/postdocs_and_students.html) you can see by yourself that the IMDEA Software students ( listed under "Research students" ) have an IMDEA [faculty](http://software.imdea.org/people/faculty.html) supervisor.

**Comment by emeryberger** [comment]
OK, thanks for the clarification.

**Pull request merged**
