### PR TITLE
Add ECE faculty at uWaterloo that work in relevant areas.

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

**Comment by emeryberger** [comment]
The current inclusion criteria state that only faculty who can advise PhD students in CS can be included. Is that the case for these faculty?

**Comment by wmdietl** [comment]
Yes, that is the case.

**Comment by emeryberger** [comment]
Can you point me to a web page indicating such? The CS cross-appointment page does not list a number of these.

https://cs.uwaterloo.ca/about/people/group/40

**Comment by wmdietl** [comment]
I based it on https://uwaterloo.ca/electrical-computer-engineering/research/areas-research/computer-software

Is your requirement that faculty can supervise PhD students in CS topics or in the CS department?
I read it as the former. Some of the faculty are cross-appointed, but not all.

**Comment by emeryberger** [comment]
Belated update. The requirement is the latter (advising in the CS department or similar).

**Pull request closed without merging**
