### PR TITLE
Add IST Penn State faculty

### PR DESCRIPTION
**Pull request by davidswelt**
Add David Reitter, Jessie Li, John Yen

### CODE REVIEW

**Comment by fycus-tree** [comment]
[IST's PhD](https://ist.psu.edu/education/degree/phd) is separate from the [EECS PhD](http://www.eecs.psu.edu/departments/EECS-Departments-Computer-Science-Engineering3.aspx). Can CS PhD students take IST advisors?

**Comment by davidswelt** [comment]
Several of us at IST are on committees (even as co-chairs) of students in the EECS PhD, and vice versa.
 
But more importantly, I would argue that PSU effectively has two CS departments, as can be seen by looking at where we publish (consider C. Lee Giles, Peng Liu, Zhenhui Li).

**Comment by fycus-tree** [comment]
The FAQ says
> __who can **solely** advise PhD students in Computer Science__ can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students.

**Comment by davidswelt** [comment]
Yes, I did read that.  At Penn State, we have Computer Science and Engineering on the one side, and Information Sciences and Technology on the other.  One is CS theory/engineering, the other one is applied CS.   Hence my submission.

**Comment by fycus-tree** [comment]
@davidswelt To me, this seems similar to #604 and #850 . Namely, a non-CS department that does some CS subfields. Neither of those have been accepted yet. IST seems even more disparate than the Cornell example, as they're at least in the same university division. At Penn, IST is a separate college entirely.

**Comment by emeryberger** [comment]
As @fycus-tree observes, the inclusion criteria require sole supervision of PhD students in CS (not another department, as is the case here). Note that an adjunct appointment in CS (as long as it permits sole supervision of a PhD student) suffices.

**Pull request closed without merging**
