### PR TITLE
Systematically rebuilt the faculty list for Peking University

### PR DESCRIPTION
**Pull request by xiongyingfei**
This commit systematically rebuilt the dataset for Peking University by the following changes.
(1) Removed all old records (which contains a lot of errors and omissions) from Peking University
(2) Added faculty at EECS (listed at: http://eecs.pku.edu.cn/EN/People/Faculty/) and ICST (listed at: http://www.icst.pku.edu.cn/index.php?s=/Home/Team/lists.html)
(3) Manually checked all DBLP entries to ensure no ambiguous page.
(4) Manually added all Google Scholar IDs.

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`. (Not needed. Already updated)

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you please pull again to resolve conflicts? Thanks.

**Comment by xiongyingfei** [comment]
Hi Emery,

I have rebased the pull request and there is no conflict now.

Regards,
Yingfei

**Comment by emeryberger** [comment]
Thanks. Could you clarify why there are two separate departments included? I can't see that they are part of the same "school" or similar. The first one (I can only see the cached version) seems to be clearly an EECS department, which is clearly eligible for inclusion, but the second appears separate. It's not clear that they both are granting PhDs _in Computer Science_ (this is of course part 1 of the inclusion criteria).

**Comment by xiongyingfei** [comment]
Yes, the first is the school of EECS as in other universities.

The second is the Institute of Computer Science and Technology and is not part of EECS. The separation of the two parts, in my understanding, is mainly historical and political. The second was initially part of the EECS and became independent later to seek more freedom in policies. Faculty members in both the school and the institute are standard faculty at Peking University and advise Ph.D. students.

I was trying to find an English page showing that the second institute recruits PH.D. student, but did not succeed as their English page is terribly incomplete. Instead, I provide the following two pages:

- http://english.pku.edu.cn/schoolsdepartments/index.htm
This page showing that ICST is officially listed as part of Peking University and is not part of EECS.

- http://www.icst.pku.edu.cn/index.php?s=/Home/Article/lists/category/students.html#yjszs
This page is in Chinese, showing that this institute is recruiting Ph.D. students.

**Comment by emeryberger** [comment]
I need some confirmation that somehow it is possible to get a PhD in CS from faculty in ICST (e.g., through cross-affiliation with EECS). Otherwise, they should be removed.

**Comment by xiongyingfei** [comment]
You may try the translated page by Google Translate: https://translate.google.com/translate?sl=zh-CN&tl=en&js=y&prev=_t&hl=zh-CN&ie=UTF-8&u=http%3A%2F%2Fwww.icst.pku.edu.cn%2Findex.php%3Fs%3D%2FHome%2FArticle%2Flists%2Fcategory%2Fstudents.html%23yjszs&edit-text=&act=url
This page shows that ICST recruits Ph.D and master student in the degree of computer science and technology (in China there is no "computer science" degree but only "computer science and technology" degree). 

And this page shows a list of Ph.D. student in computer science and technology graduated from ICST (https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=zh-CN&ie=UTF8&prev=_t&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=http://www.icst.pku.edu.cn/index.php%3Fs%3D/Home/Article/detail/id/71.html&usg=ALkJrhhF-jBz3l0pux0y1FGSZhZioaDLhw)

I see there are conflicts again. I will try to rebase.

**Comment by xiongyingfei** [comment]
Just rebased again for the newest conflict.

**Comment by emeryberger** [comment]
So to be clear: can a student get the same PhD (in the local name for Computer Science) from either EECS or ICST? Is the application process separate?

**Comment by xiongyingfei** [comment]
Can a student get the same PhD (in the local name for Computer Science) from either EECS or ICST? 
Yes.

Is the application process separate?
No. EECS is responsible for the admission process.

**Comment by emeryberger** [comment]
OK, sounds good. Thanks!

**Comment by xiongyingfei** [comment]
Great. Thanks for your hard work on the web site！

**Pull request merged**
