### PR TITLE
Tsinghua -- Added faculty information

### PR DESCRIPTION
**Pull request by llee2014**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by llee2014** [comment]
The update includes Qi Li and Chao Zhang who are the faculty members of the Institute for Network Sciences and Cyberspace, Tsinghua University. They advise PhD students in the CS department of Tsinghua University.

**Comment by emeryberger** [comment]
Your diff is too large (the entire file), probably because of line ending issues. Please open another PR or just post here (as a message) the modified lines.

**Comment by emeryberger** [comment]
(Closing for you to enter another PR; feel free to post here with updates)

**Comment by llee2014** [comment]
Please help include the following two records. Thank you!

Chao Zhang 0008 | Tsinghua University |  	http://www.insc.tsinghua.edu.cn/publish/wyy/10857/2018/20180409112456420628460/20180409112456420628460_.html | YreXlgsAAAAJ

Qi Li 0002 | Tsinghua Univerity | http://www.insc.tsinghua.edu.cn/publish/wyy/10857/2019/20190325093253944287431/20190325093253944287431_.html | NOSCHOLARPAGE

**Comment by emeryberger** [comment]
Qi Li's web page appears to be here: http://netsec.ccert.edu.cn/people/qli
Can you point somewhere that indicates that these faculty can *solely* advise CS students for a PhD *in CS*?
Same situation for Chao Zhang: http://netsec.ccert.edu.cn/people/chaoz

**Comment by llee2014** [comment]
Thanks for your feedback. The faculty members at Tsinghua cannot easily change their own homepages hosted in the school website. I am not sure if we have official documents in English on this. Here is a link in Chinese showing that the CS students at Tsinghua may be in different institutes:   http://www.cs.tsinghua.edu.cn/publish/cs/4723/2016/20160505085141209166544/20160505085141209166544_.html. Actually, most of their colleagues were included already, e.g., Dr. Hai-Xin Duan and Dr. Jun Bi. Although they are with the Institute for Network Sciences and Cyberspace, all their students are from computer science. I hope it helps.

**Pull request closed without merging**
