### PR TITLE
added 8 usyd staffs

### PR DESCRIPTION
**Pull request by i-lovelife**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [Done] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [Done] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [Done ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ Done] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [Done ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [Done ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
Many of these are not tenure-track faculty?

**Comment by i-lovelife** [comment]
Hi, Australia don't have a tenure system like US, see [this](https://www.quora.com/Does-tenure-exist-in-Australian-academia). All of them are tenured academics and eligible to advise a PHD student, so please accept this pr.

**Comment by fycus-tree** [comment]
Chang Xu is listed as a lecturer, while Dong Xu is listed as a professor. It would seem that only the the latter qualifies?

**Comment by i-lovelife** [comment]
Now I removed two lecturers, is rest of them ok to be added?

**Comment by emeryberger** [comment]
Hi - please resolve conflicts and try again. Thanks.

**Comment by emeryberger** [comment]
Closing for lack of response in two weeks. Feel free to reopen.

**Pull request closed without merging**
