### PR TITLE
Add Chulalongkorn University

### PR DESCRIPTION
**Pull request by PattaraS**
Add Chulalongkorn University. Faculty staffs from two departments below are added.

   1. The Department of Computer Engineering, Faculty of Engineering, CU
   2. The Department of Mathematics and Computer Science, Faculty of Science, CU

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - only faculty from CS or who can advise CS PhD students are eligible. Please remove anyone from computer engineering who cannot advise CS PhD students. Thanks.

**Comment by PattaraS** [comment]
Hi there,

Let me explain this a little bit. In Thailand, we usually have many fancy department names. There are two popular departments that teach Computer Science; Computer Engineering and Computer Science. Literally, both departments teach Computer Science. Most professors in Computer Engineering departments have backgrounds in Computer Science (graduated abroad). They do computer science research. If one wants to study Computer Science in Thailand, he/she should also learn about Professors in Computer Engineering.

Since only research in CS is count here, and since Computer Engineering is literally Computer Science in Thailand, I think it is fair to add Computer Engineering staffs.

What do you think?
Thanks.

**Comment by emeryberger** [comment]
The point is that these are rankings of CS departments, not others. As long as the faculty are also jointly appointed / can advise CS students, then they can be included. If not, not.

(Note that the phenomenon you describe is not at all unusual.)

**Comment by PattaraS** [comment]
I see. It seems that these faculty can not be the main adviser for a CS Ph.D. student (they can only be co-adviser). Therefore, I remove them from the list as you've suggested.

**Comment by parnurzeal** [comment]
I agree with @PattaraS that it should not limited to CS. I have studied in Computer Engineering Department and we can definitely say that Computer Engineering in Chulalongkorn University is definitely comparable to CS in US. Please please reconsider this again.

Please let me know if you need any list of publications or any related data to support this.

**Comment by supasate** [comment]
Hi, I've graduated bachelor, master, and Ph.D. from Computer Engineering Department, Chulalongkorn University. I can reassure that the Computer Engineering Department in Thailand is almost the same with CS in US (the only difference is the name). You can check the BS curriculum at https://www.cp.eng.chula.ac.th/en/prospective/bachelor/.

For graduate students, we need to publish in ISI journals (for Ph.D.) and Scopus conferences (for Master) as a requirement of graduation. 

Some of our faculty publications:
- [Kunwadee Sripanidkulchai](https://scholar.google.com/citations?user=-BgxTy4AAAAJ&hl=en)
- [Chotirat Ann Ratanamahatana](https://scholar.google.com/citations?user=THsVYSUAAAAJ&hl=en)
- [Attawith Sudsang](https://scholar.google.com/citations?user=LkEPKqMAAAAJ&hl=en&oi=sra)
- [Prabhas Chongstitvatana](https://scholar.google.com/citations?hl=en&user=xr9CefMAAAAJ&view_op=list_works&sortby=pubdate)

So, I think Computer Engineering Department, Chulalongkorn University should be included in the [csrankings.org](http://csrankings.org) as well.

Thanks!

**Comment by kindraywind** [comment]
👍 

The definition of CS schools should be extended to computer science related schools.
As long as they can research and publish in the selective CS conferences, a fancy department name does not matter.

Please reconsider this.
Thanks 😃

**Comment by PattaraS** [comment]
Shall we finish this pull request first?
Maybe we can discuss this further in an issue.

**Comment by emeryberger** [comment]
Merging.

**Pull request merged**
