### PR TITLE
update waikato cs faculty

### PR DESCRIPTION
**Pull request by matthewluckie**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by Ben5000** [comment]
Link for the website for "Ryan K. L. Ko" is broken.

**Comment by matthewluckie** [comment]
https://researchers.uq.edu.au/researcher/23784 is the website for "Ryan K. L. Ko".

**Comment by Ben5000** [comment]
This is a different link than the one that is present in your committed file.

**Comment by matthewluckie** [comment]
Sorry, I didn't check the websites of people who shifted from Waikato.  Do you want me to submit a new PR or can you make the change in the merge?

**Comment by Ben5000** [comment]
Your question should be addressed to Emery B. (I was just checking the consistency of your PR, and found this inconsistency.)

**Comment by emeryberger** [comment]
Please make another PR to fix.

**Pull request merged**
