### PR TITLE
Adding Sebastian Uchitel

### PR DESCRIPTION
**Pull request by suchitel**
Hi, Adding my information in faculty-affiliations.csv and homepages.csv.

I believe I was in this list, and got removed. Perhaps I'm wrong. Anyway....

FYI, I have a joint position but have only put in my main affiliation. I think this is what is expected, right?

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi Sebastian - currently, CSrankings only supports full-time appointments. People with split appointments are not included. Is your Buenos Aires appointment full-time?

**Comment by suchitel** [comment]
Hi, 

Mi appointment is full time at University of Buenos Aires. If you need proof I can provide copy of appointment (in spanish).


S.

**Comment by emeryberger** [comment]
No hace falta. :)

**Comment by suchitel** [comment]
:-)

**Pull request merged**
