### PR TITLE
Upodate QCRI affiliation, Add Dr. Mourad

### PR DESCRIPTION
**Pull request by ahmed451**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please pull to update & resolve conflicts and try again, thanks.

**Comment by emeryberger** [comment]
Could you explain what the story is here? It seems QCRI is just an institute within a university, so the university should be listed, not the institute (unless I am missing something).

**Comment by emeryberger** [comment]
Per the web page: " the Qatar Computing Research Institute (QCRI), an esteemed research institute that’s part of Hamad Bin Khalifa University in Doha."

**Comment by ahmed451** [comment]
QCRI started as an independent national research institute and operated 6 years as such.  I.e. publications are under QCRI.  Recently QCRI become an affiliated under HBKU, but researchers continue to be known under the brand name QCRI. This affiliation is more a management rather than an institutional affiliation as indicated the page http://www.qcri.org/about-qcri :  "Qatar Computing Research Institute (QCRI) is a national research institute, established in 2010 by Qatar Foundation for Education, Science and Community Development, a private, non-profit organization that is supporting Qatar's transformation from carbon economy to knowledge economy.  **QCRI operates under the umbrella of Hamad bin Khalifa University**."

**Comment by emeryberger** [comment]
OK. Please restore the apparent duplicates; all aliases need to be present.

**Comment by emeryberger** [comment]
Thanks!

**Comment by ahmed451** [comment]
Great. Thank you.

**Pull request merged**
