### PR TITLE
Added numerous universities globally (Aberystwyth, AU Cairo, Birkbeck, Iran University of Science and Technology, Jordan University of Science and Technology, Lancaster, Loughborough, Memorial, Ontario Tech, Open University UK, RMC Canada, Sherbrooke, Haifa, Regina, Windsor and Weizmann).

### PR DESCRIPTION
**Pull request by VishalWilde**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Thanks for all these!

**Comment by emeryberger** [comment]
One note: I am a bit surprised to not see any aliases (which would go into `dblp-aliases.csv`)...I suspect some must have been missed.

**Comment by VishalWilde** [comment]
Welcome. 

Yes, most of the time, I do not encounter alternative aliases. However, when I do, it’s usually an alias on DBLP that has perhaps one or two publications from many years ago (with the name I include in the CSRankings file containing most of the publications, being updated more frequently and having the relevant publications). Usually, as far as I could tell, these publications on the alternative alias are from many years ago and would not even be the kind that ‘register’ for scoring / adjusted count purposes by the database’s criteria so I end up skipping them to save some trouble (especially since I’m not sure if the DBLP aliases file will be sorted in the same way that CSRankings csv file is...). If I can input the DBLP aliases at the top of the respective csv file, happy to do so in future.

Finally, sometimes faculty have their articles on the ‘disambiguation’ pages and I have to skip them where they don’t clearly have an author page on DBLP. I’m not used to working with / emailing DBLP but my view is that faculty seem to increasingly care about how they ‘stack up’ on CSRankings so they will want to form that DBLP page in future  and add themselves into CSRankings accordingly. 

Obviously, I prefer it when things are perfect  but, more often than not, I’m content with a sufficient standard that can be delivered in a timely manner. 

Hope that makes sense!

**Comment by emeryberger** [comment]
Yep, I appreciate the contributions!

* I agree: If these aliases are rare or correspond to very few, old pubs, that's just fine.
* If you do see the need to add something, in principle, my cleaning script sorts `dblp-aliases.csv`.
* I have informed the kind folks at DBLP about a number of disambiguation pages and they have been quite responsive about fixing them (which I imagine is a time-consuming process).

Thanks again!

**Comment by AminTaheri23** [comment]
Hello there,

I wanted to add the faculty for my university because they were not on the website. But I can see that they are added here. Is it because the faculty was not added to [a-z] CSV? Because the contribution for the Memorial University of Newfoundland, for example, happened here, but the results on the website are not updated. Also, I can see entries in the [a-z] files now. like this https://github.com/emeryberger/CSrankings/blob/gh-pages/csrankings-l.csv#:~:text=Memorial%20University%20of%20Newfoundland 

This merge happened in 2020. So the website should've been updated in a quarterly matter a couple of times by now. 

@emeryberger Do you have any idea why this happened?

**Pull request merged**
