### PR TITLE
Add a KAIST professor left out

### PR DESCRIPTION
**Pull request by jeongseokson**
Working on Design Automation

### CODE REVIEW

**Comment by emeryberger** [comment]
Not clear this faculty member meets the inclusion criteria (in EE, not CS). Please clarify.

**Comment by jeongseokson** [comment]
I think EE (and ECE) should be considered CS-similar department, and you already have included ECE professors of other universities such as CMU, Cornell, and UIUC.

Some universities have consolidated EECS department (e.g. Berkeley, MIT, Michigan). If we distinguish CS and EE (or ECE), those universities with EECS department will clearly be advantageous.

Or do you want to distinguish EE and ECE? Some universities such as KAIST has EE instead of ECE, and many professors who are working on Computer Engineering area at KAIST belong to EE dept.

As you know, there is no strict borderline between CS and EE and each university draws a line in different ways (EECS, CS/ECE, CS/EE, CSE/EE, etc.) for various reasons. To fairly compare different universities with different department structure, I believe we should just include CS/EE/ECE/EECS professors but carefully choose prestigious conferences of CS subfields.

**Comment by emeryberger** [comment]
To be clear, the primary audience of CSRankings is graduate students in CS. The faculty listed in those places meet the inclusion criteria: they can advise a CS student for a PhD in CS. EE or ECE faculty who cannot are not included: if a graduate student in CS cannot have such faculty as advisors, then it would be misleading to include them.

**Comment by emeryberger** [comment]
I'd appreciate a PR to remove all faculty from the database who do not meet the inclusion criteria (not listed here as faculty or affiliate faculty: https://cs.kaist.ac.kr/).

**Pull request closed without merging**
