### PR TITLE
New faculty penn state

### PR DESCRIPTION
**Pull request by saptab**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
This diff of `csrankings.csv` is over 30K lines long. Possibly a line ending issue. Anyway, needs to be fixed.

**Comment by saptab** [comment]
Hi, I guess, it is because, I removed the older file with 16006 entries and added the same file with the 10 more entries which has 16016 entries. Thus, the diff is showing 16016 insertions and 16006 deletion. Please consider.

**Comment by emeryberger** [comment]
Sorry, I can't take a diff this big. Please try again.

**Comment by saptab** [comment]
Hi, diff is showing the same output in my local repository. Can I email you the 10 entries for your kind consideration?

**Comment by emeryberger** [comment]
Post them inline in a comment here.

**Comment by saptab** [comment]
Please consider the following 10 entries for csrankings

Rebecca J. Passonneau,Pennsylvania State University,https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=rjp49,jb9VOp0AAAAJ,,
Mary Beth Rosson,Pennsylvania State University,https://mrosson.ist.psu.edu/,1GUWOTEAAAAJ,,
Vasant G. Honavar,Pennsylvania State University,https://www.ist.psu.edu/directory/faculty/vuh14,pD_y458AAAAJ,,
James Ze Wang,Pennsylvania State University,https://ist.psu.edu/directory/faculty/jzw11,inVzWAcAAAAJ,,
John Yen,Pennsylvania State University,https://ist.psu.edu/directory/faculty/juy1,DxqKhDcAAAAJ,,
Jia Li 0001,Pennsylvania State University,http://personal.psu.edu/jol2/,4Nmf18IAAAAJ,,
Prasenjit Mitra,Pennsylvania State University,http://www.personal.psu.edu/pum10/,8PbgiPkAAAAJ,,
Chao-Hsien Chu,Pennsylvania State University,https://ist.psu.edu/directory/faculty/chc4,xdH7WU8AAAAJ,,
Frank E. Ritter ,Pennsylvania State University,https://ist.psu.edu/directory/faculty/fer2,i6-z9acAAAAJ,,
Ting He 0001,Pennsylvania State University,https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=tzh58,g9yS74gAAAAJ,,

**Comment by emeryberger** [comment]
Please trim this list to the faculty that appear here:
https://www.eecs.psu.edu/departments/cse-faculty-list.aspx

Faculty are only eligible when they can _solely_ advise PhD students _in Computer Science_.

**Comment by saptab** [comment]
Please note that the following 3 names appear in that list  of EECS:

Rebecca J. Passonneau,Pennsylvania State University,https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=rjp49,jb9VOp0AAAAJ,,
Vasant G. Honavar,Pennsylvania State University,https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=vuh11/vuh14,pD_y458AAAAJ,,
Ting He 0001,Pennsylvania State University,https://www.eecs.psu.edu/departments/directory-detail-g.aspx?q=tzh58,g9yS74gAAAAJ,,

Please note that the following 6 names, below are from IST which is Information Science and Technology, that is closely aligned to Computer Science as defined in the guidelines.

Mary Beth Rosson,Pennsylvania State University,https://ist.psu.edu/directory/faculty/mur13,1GUWOTEAAAAJ,,
James Ze Wang,Pennsylvania State University,https://ist.psu.edu/directory/faculty/jzw11,inVzWAcAAAAJ,,
John Yen,Pennsylvania State University,https://ist.psu.edu/directory/faculty/juy1,DxqKhDcAAAAJ,,
Prasenjit Mitra,Pennsylvania State University,https://ist.psu.edu/directory/faculty/pum10,8PbgiPkAAAAJ,,
Chao-Hsien Chu,Pennsylvania State University,https://ist.psu.edu/directory/faculty/chc4,xdH7WU8AAAAJ,,
Frank E. Ritter ,Pennsylvania State University,https://ist.psu.edu/directory/faculty/fer2,i6-z9acAAAAJ,,

**Comment by emeryberger** [comment]
The guidelines are pretty clear. They must be able to solely advise PhD students _in CS_. In an institution like Penn State where there is a Computer Science department, included faculty need to be either part of that department or otherwise able to advise PhD students in that department, e.g., via secondary / joint appointments.

**Comment by emeryberger** [comment]
I have manually added the first three faculty.

**Comment by saptab** [comment]
Thank you very much for kindly clarifying. Thank you so much for kindly adding the first three faculty.

**Pull request closed without merging**
