### PR TITLE
Added faculties from ShanghaiTech University

### PR DESCRIPTION
**Pull request by TachikakaMin**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

PhD: http://sist.shanghaitech.edu.cn/2826/list.htm

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Two things:
(1) There are some conflicts. Please resolve them.
(2) Please point to a page indicating that this institution offers a PhD in Computer Science.

**Comment by TachikakaMin** [comment]
> Two things:
> (1) There are some conflicts. Please resolve them.
> (2) Please point to a page indicating that this institution offers a PhD in Computer Science.

There is no conflict now. Thank you.

**Comment by emeryberger** [comment]
Please address point (2) in my comment above.

**Comment by TachikakaMin** [comment]
> Please address point (2) in my comment above.

I have updated it above. However, there is only a Chinese version that I can find on the website.

PhD: http://sist.shanghaitech.edu.cn/2826/list.htm

**Comment by emeryberger** [comment]
Sorry, new conflicts. Also, I don't see "computer science" as the degree program...

**Comment by emeryberger** [comment]
Closing for lack of response. Please feel free to re-open.

**Pull request closed without merging**
