### PR TITLE
add Eurographics conference

### PR DESCRIPTION
**Pull request by salzrat**
I am a professor in Computer Graphics and create this pull request on behalf of the the Conference Steering Committee of the Eurographics Association (www.eg.org). 

We have noticed that csranking only includes the ACM Siggraph and Siggraph Asia conferences in the "Graphics" category. We would like to request to also include the annual Eurographics Conference (e.g., https://eg2022.univ-reims.fr/) in the ranking:
https://dblp.org/db/conf/eurographics/index.html

The Eurographics Conference exists since 1980, and is the most important conference for computer graphics research in Europe. Its full paper program has similar acceptance rates as Siggraph and Siggraph Asia: in the recent years, slightly above 30%, similar to those two conferences, and before around 20%, often more selective than Siggraph or Siggraph Asia. And while submission numbers are not as high as Siggraph, they are the highest for any graphics conference beyond the two ACM conferences, and have for many years been competitive with Siggraph Asia.

The computer vision field also includes the main European CV conference (ECCV), and we believe that it would be important for geographic diversity to include the conference in an area which has one of the highest numbers of computer graphics researchers worldwide.

If you require any further information, please don't hesitate to respond here.

### CODE REVIEW

**Review by salzrat — COMMENTED** [review]
(note that I have tried to include Eurographics in the same way as Siggraph, but I am not sure I caught all places where code needs to be changed)

**Comment by emeryberger** [comment]
Only venues in the same equivalence class can be listed "above the fold" in CSrankings. SIGGRAPH and SIGGRAPH Asia are published in TOG, and Eurographics is published in CGF; those two publications are clearly substantially different on the basis of metrics alone. See https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_computergraphics.

There would, however, be a reasonable case to be made to add Eurographics as a below-the-fold venue (off by default); I would be willing to consider a PR that did that.

**Comment by salzrat** [comment]
Thank you for the swift reply! Is there a clear definition what is "above the fold" and "below the fold"? I read that you include up to 3 conferences for each area. 

How would I create a PR to include Eurographics "below the fold"?
Thanks!

**Comment by emeryberger** [comment]
The top conferences -- at most 3 -- need to be in a single equivalence class (indisputably top venues). You can see in the code that there are a number of "below the fold" / "next tier" conferences (not on by default); see https://github.com/emeryberger/CSrankings/blob/f64f217b9ae553e1c0441071fcc33b19e3c5c2ef/csrankings.ts#L335.

**Comment by salzrat** [comment]
So would adding
`'eurographics': true,`
to nextTier make this a suitable PR?

**Comment by emeryberger** [comment]
It also would need to appear below the fold in the HTML.

**Comment by salzrat** [comment]
I added it to the html as well. Could you check whether it is now sufficient? Thanks!

**Comment by salzrat** [comment]
Any updates on this? Do I need to provide something else?

**Comment by emeryberger** [comment]
I've merged this with https://github.com/emeryberger/CSrankings/commit/a8b843e5456beb2a43fd1d14f4c1f2cc47c3cd0a but temporarily disabled it - I had to add the journal to `filter.xq` and then will activate it once I update the database.

**Comment by salzrat** [comment]
Thanks!

**Pull request merged**
