### PR TITLE
Update IIT Patna faculty

### PR DESCRIPTION
**Pull request by respel**

### CODE REVIEW

**Comment by emeryberger** [comment]
I am going to revert this:
https://www.iitp.ac.in/index.php/the-institute/administration/administrators/directorate/1821-directors-profile.html

**Comment by respel** [comment]
Pushpak Bhattacharya still mentions IIT Bombay as his institution instead of IIT Patna. Here is a recent AAAI paper as an example[1]. He mentions his designation as "Director"(IIT Patna) and "Prof of Computer Science" (IIT Bombay)[2]. So he sees the position at IIT Patna more of an administrative position than anything else.

Hope this convinces you.

[1]-https://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14867/14049 
[2] - https://www.iitp.ac.in/index.php/the-institute/administration/administrators/directorate/1822-prof-pushpak-bhattacharyya-cv.html

**Comment by emeryberger** [comment]
It's difficult for me to see how the role of director could be compatible with being a full-time faculty member at another institution.

**Comment by respel** [comment]
Beats me too but that is what his own his opinion is.

**Pull request merged**
