### PR TITLE
Add Bielefeld University 

### PR DESCRIPTION
**Pull request by ghost**
Updated country, faculty-affiliations and homepages.csv to include Bielefeld University. If there are any problems, please let me know.

### CODE REVIEW

**Comment by emeryberger** [comment]
The diff is too large to inspect, which probably means the line endings have changed. Please run `dos2unix` on the files and re-commit. Thanks.

**Comment by emeryberger** [comment]
Hi - please do this for the homepages file as well. Thanks.

**Comment by ghost** [comment]
Hey there~
The diffs are now manageable in the latest commit.

**Comment by emeryberger** [comment]
Great - please resolve the conflicts and I will merge.

**Comment by ghost** [comment]
Please excuse my inexperience, this is my first public pull request. 
Edit/Update:
-  fetched and resetted local to the latest branch (b29b9c7)
- put affiliation/homepages/countryinfo in csv
- instead of manually sorting the data in like last time, i used sublime-texts "Sort Lines" on a unix system instead, to hopefully have no trouble with the diff / the line endings
- ran dos2unix on all 3 files anyway
- pushed all of that 

The branch now has no conflicts from the get-go, but you still cannot view the full diff. I'm somewhat lost, the problem might be something else. 
Should I just close this request and start-over, manually sorting the entries and opening a new pull request?

**Comment by emeryberger** [comment]
When you perform `make`, it already sorts things in the appropriate way. I can't easily merge this right now. I think the best thing right now would be to start over; I am going to close this one. Fork the current repo, merge in your changes, and do another PR. Thanks.

**Pull request closed without merging**
