### PR TITLE
Added faculty of École Normale Supérieure de Cachan

### PR DESCRIPTION
**Pull request by sylvainschmitz**
Added an institution with its faculty.  CS faculty at ENS Cachan tends to specialize in logic.

Also fixed the missing joint CSL-LICS conference from 2014.

### CODE REVIEW

**Comment by emeryberger** [comment]
Web page says there are ~19 faculty but this PR has more. Only the equivalent of full-time, tenure-track CS faculty should be included (http://www.ens-cachan.fr/version-anglaise/education/computer-science-department-18456.kjsp?RH=ACCUEIL_GB).

**Comment by sylvainschmitz** [comment]
Welcome to the intricacies of the French higher education system :)  The list I gave includes permanent full-time researchers, who have no teaching obligation; see http://www.lsv.ens-cachan.fr/People/

**Comment by emeryberger** [comment]
Please make separate PRs for each institution.

**Comment by sylvainschmitz** [comment]
Sorry, I hadn't realised that pushing changes after the pull request would change its contents.

**Comment by emeryberger** [comment]
Are Univ of Bordeaux faculty still included? Also, the number of faculty for both Warsaw and Bordeaux seems awfully high.

**Comment by sylvainschmitz** [comment]
This pull request only contains the faculty from ENS Cachan and the fix for CSL-LICS 2014.

Regarding big faculties, yes, e.g. the CS lab in Bordeaux has 169 permanent researchers (http://www.labri.fr/index.php?n=Annuaires.Personnel&macategorie=0 ; MdC stands for tenured assistant professor, Pr for professor, CR for tenured junior researcher, DR for senior researcher).  In France and Poland, there seem to be many more tenured or tenured-track positions than in the US (presumably we have fewer teaching assistants).  I indicated the source URI with the commits.

**Comment by emeryberger** [comment]
Are those folks really all "tenure-track faculty" as we would consider them here? That is, they are full-time employed and they are salaried (their funding is not dependent on securing grants)? For the US, the latter (called "research faculty") are currently excluded. Are tenured junior researchers past their PhD?

**Comment by sylvainschmitz** [comment]
The answer is yes for all questions.  They are actually already tenured; more precisely they are civil servants with guaranteed life-time employment.

One more thing that might appear unusual is that CR/DR are actually paid by research institutions distinct from the universities (for computer science, CNRS and INRIA).  But yes, their positions are full-time, salaried, independent from any grants, and post-PhD.  Most of those researchers work in joint labs with universities, and it makes more sense to count them as part of the university faculty (anyhow they often teach there as well, although they have no contractual obligation to do so), as the alternative would be to have two gigantic lists for CNRS and INRIA over the whole of France.  The choice of counting them as part of the university faculty is also consistent with the listing you had for Ecole Normale Superieure, where you included several INRIA and CNRS researchers.

**Pull request merged**
