### PR TITLE
Technion update

### PR DESCRIPTION
**Pull request by annabel8**
The pull request adds full-time, tenure-track faculty members from the Technion that are computer scientists formally affiliated with the Faculty of Industrial Engineering and Management. All the faculty members on the list can (and do) advise PhD students in Computer Science. The pull request is done on behalf of Prof. Carmel Domshlak, Dean of the IE&M Faculty (iedean@technion.ac.il) and Prof. Dan Geiger, Dean of the CS Faculty (dean@cs.technion.ac.il) at the Technion.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please point to documentation, preferably on the Technion CS dept. website, that shows that these faculty have a formal affiliation with the CS dept. and can thus *singly* advise PhD students in Computer Science. Thanks.

**Comment by annabel8** [comment]
Thank you for your quick response. I'm answering on behalf of  Prof. Carmel Domshlak.

Secondary affiliations at the Technion almost do not exist (there are only a dozen such secondary affiliations across the entire institute, and most of them are old days legacy). Thus, advising a student from CS (or from any other academic unit for that matter) requires only approval of the CS faculty. Will an email from the CS Dean satisfy the verification procedure?

**Comment by emeryberger** [comment]
An email from the Dean (which I will post here) should suffice.
In addition, the diff is too large to audit; please submit a clean commit that just adds the relevant faculty so it is auditable.

**Comment by annabel8** [comment]
Hi, an email for the CS Dean was sent to you. Can I proceed and submit a clean commit?
Many Thanks!

**Comment by emeryberger** [comment]
I sent a note requesting further clarification. In the meanwhile, please resolve the conflicts and re-submit. Thanks.

**Comment by emeryberger** [comment]
Here is the text of the note from the Dean of CS at Technion: "I confirm that the faculty members from the IE&M faculty at the Technion are eligible to advise graduate students at the CS faculty at the Technion." (clarified: they can do this solely).

As soon as the conflicts are resolved, I will merge.

**Comment by emeryberger** [comment]
Please restrict the commit to the Technion faculty being added - thanks.

**Comment by annabel8** [comment]
Hi, I hope it is OK now. The differences from previous commit are only whitespaces.
Thank you!

**Comment by emeryberger** [comment]
Perfect, thanks!

**Pull request merged**
