### PR TITLE
Update computer architecture faculty at U of Toronto and MIT

### PR DESCRIPTION
**Pull request by markcjeffrey**

### CODE REVIEW

**Comment by emeryberger** [comment]
Thanks for the fix of Daniel's last name (will change now). The other two do not meet the current inclusion criteria because they apparently can't advise CS PhD students at Toronto (see http://web.cs.toronto.edu/people/faculty.htm as well as https://github.com/emeryberger/CSrankings/blob/gh-pages/CONTRIBUTING.md).

**Comment by markcjeffrey** [comment]
Just to clarify, Daniel spells his last name Sanchez, but DBLP doesn’t
notice that and uses the accent.

Too bad about Natalie and Andreas at U of T. Computer Architecture is a
field that sometimes spans CS and ECE departments. There can’t be any
exception for that?

**Comment by emeryberger** [comment]
Right, I fixed the accent. I thought I had correctly put in his name before but either I forgot or DBLP changed.

I am only too aware of the issue with computer architecture. Many computer architects have joint appointments or at least adjunct status so they can supervise CS PhDs even though they are in ECE departments. (It's "CSrankings", after all...)

**Comment by markcjeffrey** [comment]
Good point! Thanks for managing this website.

**Pull request closed without merging**
