### PR TITLE
Replace pie charts with bar charts using Vega

### PR DESCRIPTION
**Pull request by minsukkahng**
Hi Emery,

This PR replaces **pie charts**, used for visualizing the distribution of publication areas for institutions/authors, with **bar charts**.

Although pie charts are common, they are generally not recommended when many data items are presented. Bar charts are generally more effective at performing data analysis tasks by users. The following article written by a visualization researcher talks more about pie charts: https://eagereyes.org/pie-charts.

As a data visualization researcher, I wanted to make a contribution to CSRankings by redesigning the charts. To do it, I've rewritten the makeChart function and used [Vega](https://vega.github.io/vega/), a well-known data visualization library created by by a team of visualization researchers from UW.

Two figures below show differences between the current and new charts. One benefit is the bar charts save much vertical space, which enables users to compare multiple institutions or author profiles without having to scroll.

***Institution profile:***

***Author profile:***

Thank you for your consideration.

Cheers,
Minsuk

--
Minsuk Kahng
Assistant Professor
Oregon State University
https://minsuk.com

### CODE REVIEW

**Review by emeryberger — APPROVED** [review]
LGTM. Some nice code cleanup to boot, thanks!

**Comment by emeryberger** [comment]
Thanks for this excellent contribution! This overall looks fantastic and I'm eager to merge it. I have a few requests:

1. Rather than eliminating the pie charts completely, I'd like the choice to be controlled by a runtime switch (possibly exposed via the URL; if it's just a compile-time setting for now, that would be fine). Note that this would need to preserve the explanatory text in the header as well.
2. Please switch to [this color scheme](https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=4) for the charts and the mini-icons.

Thanks!

**Comment by emeryberger** [comment]
I'm going to go ahead and merge in the interest of expediency; if you can attend to the above requests with subsequent PRs (I'll deal with the color changes :) ), that'd be great. Thanks again!

**Comment by minsukkahng** [comment]
Thank you very much for quickly reviewing and accepting my PR. Excited!

I'll send you two subsequent PRs for your requests in a few minutes.

Cheers,
Minsuk

**Pull request merged**
