### PR TITLE
Changing the affiliation 'DIKU' to 'University of Copenhagen'

### PR DESCRIPTION
**Pull request by isabelleaugenstein**
Changing the affiliation 'DIKU' (which is a department at the University of Copenhagen) to 'University of Copenhagen' to be in line with other institution entries

### CODE REVIEW

**Comment by emeryberger** [comment]
There are quite a few other institutions that are abbreviated but this is fine with me.

**Comment by emeryberger** [comment]
It also needs to be changed in `country-info.csv`.

**Comment by isabelleaugenstein** [comment]
Thanks! I've changed this in the `country-info.csv` as well

**Comment by emeryberger** [comment]
Done - thanks!

**Pull request merged**
