### PR TITLE
Add "Viet Tung Hoang"

### PR DESCRIPTION
**Pull request by hviettung**
Add a new faculty.

### CODE REVIEW

**Comment by emeryberger** [comment]
This commit has a number of spurious #NAME? entries. These need to be removed.

**Comment by hviettung** [comment]
>> This commit has a number of spurious #NAME? entries
I fixed the incompatibility issues caused by MS Excel.

**Comment by emeryberger** [comment]
I am still seeing too many lines in the diff. Again, probably a line ending issue.

**Comment by emeryberger** [comment]
Closing for lack of response.

**Pull request closed without merging**
