### PR TITLE
Adding Charles University - UFAL

### PR DESCRIPTION
**Pull request by obo**
Dear CSrankings maintainers,

I would like to add our department. Unfortunately, I don't have the data to add the whole Faculty of Mathematics and Physics (which includes not only other departments of the school of computer science but also many maths and physics departments).

Could our department be nevertheless added?

Thank you, Ondrej Bojar.

### CODE REVIEW

**Comment by emeryberger** [comment]
This commit has too many diffs for me to audit; can you please re-pull and commit only your changes? (If this is the exhaustive list of members of the CS department, that's perfect.)

**Comment by obo** [comment]
Dear Emery,

I can do the suggested re-pull, but I'd still like you to reconsider my pull request, diff-by-diff. It's three diffs altogether:

1. Sorting your file using "LC_ALL=C sort", this makes it easier to reproduce on different setups and thus easier to integrate longer lists of people for anyone.

2. Adding our department (but only NLP, not the whole CS)
3. A minor fix of our names to match DBLP.

(2&3 should have been done in one commit, my fault, apologies. I can redo it if your really care about the beauty of the past.)

The step 1 is however something that I think should be done for the common good anyway.

A good option would be also that *you* do the "LC_ALL=C sort", and only then I will add our people, now in one commit and not with the error correction.

Thanks,
  Ondrej.

----- Original Message -----
> From: "Emery Berger" <notifications@github.com>
> To: "emeryberger/CSrankings" <CSrankings@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Friday, 28 September, 2018 18:44:29
> Subject: Re: [emeryberger/CSrankings] Adding Charles University - UFAL (#1054)

> This commit has too many diffs for me to audit; can you please re-pull and
> commit only your changes? (If this is the exhaustive list of members of the CS
> department, that's perfect.)
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/emeryberger/CSrankings/pull/1054#issuecomment-425586313

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by emeryberger** [comment]
The file is actually sorted via a Python program, not `sort`. Anyway, please pull and resolve conflicts.

**Comment by emeryberger** [comment]
Closing because of lack of response; please feel free to re-open.

**Pull request closed without merging**
