### PR TITLE
Adding few Canadian Universities' Profs

### PR DESCRIPTION
**Pull request by quettabit**

### CODE REVIEW

**Comment by emeryberger** [comment]
The presence of other people who do not meet the inclusion criteria is an oversight, not a reason for letting other faculty in. If Joelle's appointment is < 9 months at McGill (e.g., she is on leave, or at 50% status), then she cannot be included.

Also, we do not (deliberately) include faculty whose DBLP entries are ambiguous. You can see this in some open issues right now.

**Comment by quettabit** [comment]
Cool. I think we should include this as well in the Contribution Guidelines.

**Comment by quettabit** [comment]
@emeryberger Doing the needs as requested :+1:

**Comment by emeryberger** [comment]
Good idea on the contributions question. Thanks!

**Pull request merged**
