### PR TITLE
Updating Contribution guidelines re: partial appointments and adding one faculty member

### PR DESCRIPTION
**Pull request by jkkummerfeld**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to convert some Google Scholar entries to formulas, corrupting the database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion criteria. Eligible faculty include only full-time, tenure-track faculty members on a given campus who can *solely* advise PhD students in Computer Science. Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US, update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
A number of these folks are on leave or have < 75% time appointments, as has been previously confirmed. Please remove everyone who is listed in `old/industry.csv`.

**Comment by jkkummerfeld** [comment]
Done, I didn't realise that was part of the criteria, sorry!

I'd be happy to propose a PR to add that to `CONTRIBUTING.md` if you'd like.

**Comment by jkkummerfeld** [comment]
Two other notes:
- I left the DBLP aliases in figuring it would be convenient to have them if they shift back to being 75%+ in their role.
- Some of these people are teaching faculty, but my understanding is that their role does permit / include student advising (e.g. John DeNero is a "Associate Teaching Professor", a tenure track primarily teaching position)

**Comment by emeryberger** [comment]
Good idea on `CONTRIBUTING.md` - that'd be great.

DBLP aliases: yes, please leave them.
Teaching faculty: not eligible for inclusion; the criteria are specifically tenure-track only.

Thanks!

**Comment by jkkummerfeld** [comment]
Removing the teaching faculty leaves this PR as just one extra faculty member, so I made the `CONTRIBUTING.md` edits here too. Note that I added the word 'research' to clarify the teaching point (I know that at Berkeley "Associate Teaching Professor" *is* a tenure-track position even though it is primarily teaching focused, so 'tenure-track' is insufficient as a label).

**Comment by emeryberger** [comment]
Many thanks!

**Pull request merged**
