### PR TITLE
Split mlmining into ML and KDD. Also add CIKM, JMLR as second tier only.

### PR DESCRIPTION
**Pull request by kno10**
The ML field is quite diverse. There is the NIPS-ICML world, and the KDD/SDM/ICDM world.
These deserve to be treated similar.

Not sure what would be the best third venue for NIPS-ICML (because there also is AI separately), I put in JMLR as second tier. These days NIPS and ICML publish so many papers, two is probably enough.
CIKM would likely fit the IR/WWW pair, but I put it in as second tier only + these two are also extremely big.

### CODE REVIEW

**Comment by kno10** [comment]
Of course some people will say there are not two communities, but in fact there are.

Some very prolific examples:
Christos Faloutsos: 64 KDD, 30 SDM, 26 ICDM - 0 NIPS, 1 ICML - 610 total
Jiawei Han:  83 KDD, 31 SDM, 45 ICDM - 3 NIPS, 2 ICML - 881 total
Philip S. Yu: 67 KDD, 69 SDM, 68 ICDM - 2 NIPS, 6 ICML - 1208 total
Geoffrey E. Hinton: 0 KDD, 0 SDM, 0 ICDM - 59 NIPS, 13 ICML - 226 total
Yann LeCun: 1 KDD, 0 SDM, 0 ICDM - 28 NIPS, 13 ICML - 230 total
Jürgen Schmidhuber: 0 KDD, 0 SDM, 0 ICDM - 17 NIPS, 9 ICML -338 total
Pedro Domingos: 13 KDD, 0 SDM, 1 ICDM - 6 NIPS, 19 ICML - 168 total

If there are highly prolific people that have 83 KDD paper but just 2 ICML and 3 NIPS, and others with 28 NIPS, 13 ICML and 1 KDD 0 SDM 0 ICDM that clearly shows that ML and DM are related, but not the same community/subdomain.

**Comment by fycus-tree** [comment]
@kno10 I'd support and agree with this. See #859 for some technical analysis. See #238 for an issue on this topic. 

My proposal, based on unsupervised clustering of authorship embeddings, was

| Area | Venue 1 | Venue 2 | Venue 3 | Venue 4 | Venue 5 |
|----------------------|----------------------------------|----------------------------|------------------------------|-------------------|-----------------------|
| AI & ML | NIPS | AAAI | ICML | IJCAI | AISTATS |
| Data Mining | KDD | ICDM | SDM | CIKM | IEEE-TKE |

That is, I think there's a strong technical/quantitative argument for the separation. That split was also done by this [arXiv paper](https://arxiv.org/abs/1710.05225) on CSRankings data. "_we split the KDD conference into a separate ”data mining” area apart from ICML and NIPS, as the two areas had different prepublication behaviour._  " 

Edit: apologies for the spam. GitHub was having technical issues.

**Comment by emeryberger** [comment]
I appreciate this but I have placed a moratorium on new areas for CSrankings through the year (that is, 2018), so this will have to be on hold. In any case, please remove the next tier venues; those will have to be established separately.

**Comment by bhatiasiddharth** [comment]
Is there an update on this?

**Comment by kno10** [comment]
Note: if you do the same author analysis, but only taking the last 2-3 years into account, I am *not* convinced that this still holds. The data mining community has dissolved, most are doing deep learning now.

In my subjective view, you by now find more data mining papers on NeurIPS than on KDD.

**Pull request closed without merging**
