### PR TITLE
Changes to the University of Cambridge to reflect current faculty

### PR DESCRIPTION
**Pull request by timothymjones**
Added and removed people and fixed duplicates to reflect current faculty and an additional related faculty in a different department:

https://www.cl.cam.ac.uk/people/academic.html

### CODE REVIEW

**Comment by emeryberger** [comment]
Please restore "duplicates". These are aliases (look at their DBLP records) and all of them must be present. Thanks.

**Comment by timothymjones** [comment]
Perhaps I didn't explain this correctly.  I removed duplicates from csrankings.csv and then created aliases in dblp-aliases.csv instead.  For each person, I checked DBLP to see what aliases they had and added all that were relevant.  See, for example, Alan Blackwell, which I removed from csrankings.csv but added as an alias for Alan F. Blackwell in dblp-aliases.csv.

If that's wrong, or there's something else I should have done, I apologise and will fix.

Thanks
Tim

**Comment by emeryberger** [comment]
I see -- I had not noticed the updates to `dblp-aliases.csv`-- thanks! Much appreciated.

**Comment by emeryberger** [comment]
One note - I see that you restored Nada Amin; I updated her affiliation to Harvard since she announced she is joining in the coming academic year (https://www.cl.cam.ac.uk/~na482/), so I will revert that change.

**Comment by timothymjones** [comment]
Yes, I saw she was listed as being at Harvard and saw her website.  I put her to Cambridge again since that's where she is affiliated right now and figured she'd been moved prematurely.  But if you want the rankings to reflect the future rather then the present then of course she should be affiliated to Harvard once more.

**Comment by emeryberger** [comment]
In this case, I believe it could matter for recruiting new graduate students, so having her at her new affiliation for the upcoming academic year seems the right thing to do.

**Pull request merged**
