### PR TITLE
Added faculty from CDS department at IISc, Bangalore, and their DBLP aliases

### PR DESCRIPTION
**Pull request by simmhan**
Added faculty from the Department of Computational and Data Sciences (CDS) at IISc, Bangalore, and their DBLP Alias entries, http://cds.iisc.ac.in/people/faculty/

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by simmhan** [comment]
Hi @emeryberger,

A gentle nudge on this open request. Do you see any concerns?

--Yogesh

**Comment by emeryberger** [comment]
It has conflicts that need to be resolved. Please pull again.

**Comment by emeryberger** [comment]
CDS is not CS (http://www.csa.iisc.ac.in). Faculty in this department do not appear to have affiliate status with CS and are not otherwise listed (https://www.csa.iisc.ac.in/people/people-faculty.php), meaning they are presumptively ineligible for inclusion. Feel free to re-open with evidence indicating they meet the inclusion criteria.

**Comment by simmhan** [comment]
Hi @emeryberger,

IISc has two departments that have computer science based programs, Computer Science and Automation (CSA) and Computational and Data Sciences (CDS). Both these departments offer independent PhD programs, and have faculty with CS training. While some faculty request courtesy appointments from CDS at CSA, it is a personal choice.
http://cds.iisc.ac.in/people/faculty/
http://cds.iisc.ac.in/admissions/research-degrees/

This is similar to the twin Computer Science (CS) and Computational Science and Engineering (CSE) programs at Georgia Tech, faculty from both of which I see are listed on CSRankings.
https://scs.gatech.edu/people/faculty
https://cse.gatech.edu/people/faculty

**Comment by codope** [comment]
@emeryberger @simmhan Request to revive this PR. Many prospective students visit csrankings.org and it would be so helpful for them to discover more researchers in their area of interest. @simmhan has also mentioned a similar example from Georgia Tech. If we are  aligned, I can help in updating the PR (or rather create a new one) based on the latest [faculty list](https://cds.iisc.ac.in/people-all/faculty/).

**Comment by emeryberger** [comment]
Only faculty meeting the inclusion criteria can be included; if they cannot solely advise PhD students for a PhD _in Computer Science_, they are not eligible for inclusion in CSrankings.

**Pull request closed without merging**
