### PR TITLE
New Brazilian university in the list

### PR DESCRIPTION
**Pull request by mcmachado**
Universidade Federal de Minas Gerais, following the website http://dcc.ufmg.br/dcc/?q=en/professores

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - the `scholar.csv`, `homepages.csv`, and `faculty-affiliations.csv` files have all been merged into `csrankings.csv`. Please submit a PR updating that file. Thanks.

**Comment by mcmachado** [comment]
@emeryberger I just finished changing everything to the new format :-)

**Comment by emeryberger** [comment]
The diffs are too large to audit (notably `csrankings.csv`) plus it includes lots of merges. It might be a `dos2unix` issue but right now I need to be able to see a smaller merge.

**Comment by mcmachado** [comment]
@emeryberger I'm very sorry to hear that.
What is weird is that when I look at the commits here in the gitHub page nothing pops up.
I did add 51 lines, I think, to `csrankings.csv`, but that was all.

What do you want me to do? I tried to put the professors in alphabetical order in the file, but another possibility is to put them all at the bottom, so the diff gets more localized.

Cheers!

**Comment by emeryberger** [comment]
How about you close this PR, fork the repo again, add the new faculty (ideally all together), and open a new PR?

**Comment by mcmachado** [comment]
Ok. I'll do it now.

**Pull request closed without merging**
