### PR TITLE
Usna faculty

### PR DESCRIPTION
**Pull request by adamaviv**
Adding Computer Science faculty from USNA

### CODE REVIEW

**Comment by adamaviv** [comment]
Please see the following website for further information:

https://www.usna.edu/CS/People/index.php

And

https://www.usna.edu/CyberDept/People/index.php

**Comment by emeryberger** [comment]
Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations by modifying `faculty-affiliations.csv`

- [ ] Change the home page by modifying the file `homepages.csv`.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name by modifying `faculty-affiliations.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] Enter their home page by modifying the file `homepages.csv`.
(CSrankings has an automatic home page generator, but it is not perfect.)

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

**Comment by emeryberger** [comment]
(bump)

**Comment by adamaviv** [comment]
Yeah, sorry. I'll do the updates today.

**Comment by adamaviv** [comment]
I've updated this pull request to include the homepages and checking the names against DBLP. Only faculty with DBLP entries were added.

**Comment by emeryberger** [comment]
I am sorry about this but I just realized that the Naval Academy doesn't grant PhDs, making it not currently eligible for CSrankings.

From the FAQ:

What are the criteria for including faculty?
--
The criteria for inclusion (which have been refined since CSRankings' inception) are that anyone who is a full-time, tenure-track faculty member on a given campus who can advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students.

**Pull request closed without merging**
