### PR TITLE
Add IU HCI group

### PR DESCRIPTION
**Pull request by rrnewton**
This adds the missing folks who publish in Chi/UbiComp/UIST.

### CODE REVIEW

**Comment by rrnewton** [comment]
CC @jsiek

**Comment by emeryberger** [comment]
I am delaying merging pending a decision on how to handle non-CS faculty.

**Comment by rrnewton** [comment]
Yeah, if there is a clear policy we need to either remove or add folks; e.g., Kay Connelly is currently included, but I don't think there's a rationale for including her but not these other folks.  IU's a complicated case in point: we don't actually have a CS _department_, just one big School of Informatics, and people's affiliations within that have been pretty fluid.

**Comment by rrnewton** [comment]
@emeryberger - I noticed on the FAQ it says that the distinguishing criteria is whether the faculty are able to advise CS Ph.D. students.  Actually, we do not have a CS Department.  There are different degrees, but we have just one unit that is "Informatics & Computing".  All of the people in this list can advise CS Ph.D. students, and many do.

I think the "can advise" distinction makes sense, because that's what's relevant to a potential CS grad applicant.

**Pull request merged**
