### PR TITLE
Update faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by luisetrodrigues**
Added Universidade de Lisboa

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - any reason this is closed?

**Comment by luisetrodrigues** [comment]
No, sorry. That was a misclik.

I would like the faculty from Universidade de Lisboa to go into the database.

Is there is something I should do to fix it?

**Comment by emeryberger** [comment]
These are full-time tenure track faculty in the CS department, correct?

**Comment by luisetrodrigues** [comment]
Some in the CS department and some in the EE department. At IST (the technical institute from ULisboa), some frontier areas such as “networks" and “computer architecture” have people active in both departments.

Thanks,

Luis

**Comment by emeryberger** [comment]
Only people who can advise PhD students in the Computer Science department may be included. If the EE faculty do not have joint appointments, they should be removed.

**Comment by luisetrodrigues** [comment]
EE faculty are allowed to supervise PhD students in CS.

However I can submit a shorter list only with CS professors, if you believe this is more appropriate.

Thanks,

Luis Rodrigues

**Comment by emeryberger** [comment]
Any faculty who can supervise PhD in CS are eligible, so this is fine. Note that the home pages will be generated automatically by a script, so you should review them (wait about 15 minutes).

**Pull request merged**
