### PR TITLE
Add faculties of Peking University

### PR DESCRIPTION
**Pull request by longo11070001**
We have checked the DBLP entries of the faculties of our school and requested unique entries for some ambiguous name. If there are any problems, please notify us. We really appreciate for your kind help. Thank you very much.

### CODE REVIEW

**Comment by emeryberger** [comment]
Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted. Please do the following / check that you have done the following.

- [ ] Correct CR/LF endings by running `dos2unix` and re-committing; diffs should not be an entire file.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations by modifying `faculty-affiliations.csv`

- [x] Change the home page by modifying the file `homepages.csv`.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name by modifying `faculty-affiliations.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] Enter their home page by modifying the file `homepages.csv`.
(CSrankings has an automatic home page generator, but it is not perfect.)

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

**Comment by emeryberger** [comment]
Bump, @longo11070001

**Comment by longo11070001** [comment]
1. The conflicts are all resolved. 
2. Aliases are added to the dblp-aliases.csv.
3. We check that the faculty we add meet the inclusion criteria.
Thanks!

**Review by emeryberger — CHANGES_REQUESTED** [review]
There should be no aliases added when the names are identical (as in X, X).

**Comment by longo11070001** [comment]
The aliases have been fixed. And the conflicts are resolved. Then, are there still any problems I didn't notice? Sorry for the bother.

**Review by emeryberger — APPROVED** [review]

**Comment by emeryberger** [comment]
Looks good now, thanks!

**Pull request merged**
