### PR TITLE
Added Faculty for UC Riverside

### PR DESCRIPTION
**Pull request by PayasR**
Added people from :
http://www1.cs.ucr.edu/people/faculty/
http://www1.cs.ucr.edu/index.php
http://www.ee.ucr.edu/people/

### CODE REVIEW

**Comment by wongdani** [comment]
Thanks Payas for adding UCR!
Since my name is common, my DBLP name is actually "Daniel Wong 0001".

**Comment by PayasR** [comment]
@wongdani Thank you Prof. Wong, I have made the changes.

**Comment by emeryberger** [comment]
Hi - for now, only CS faculty are being included (that is, from a CS department or similar); can you please revise the PR? Thanks.

**Comment by emeryberger** [comment]
Also, please break out mods to other affiliations into a different PR.

**Comment by PayasR** [comment]
@emeryberger please check now.

**Comment by PayasR** [comment]
The mods to other affiliations were a mistake in the first commit and I reverted all of those changes in the third commit. At this point, the file is exactly the same as on your repository + the UCR faculty. I don't think a separate PR would be required..

**Comment by emeryberger** [comment]
OK, though I still see numerous names that are not on the CS page  or who are specifically listed as being in another department (e.g., EE):
  Heng Yin , University of California - Riverside
  Vagelis Papalexakis , University of California - Riverside
  Mohsen Lesani , University of California - Riverside

**Comment by wongdani** [comment]
Those faculty members are new hires in the CS department who joined July 1. 
http://www1.cs.ucr.edu/index.php#in_the_news

**Comment by emeryberger** [comment]
Great, thanks!

**Pull request merged**
