### PR TITLE
Added faculty members at IISc who can advise CS students.

### PR DESCRIPTION
**Pull request by vgiiscacin**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
Can you clarify where it says that they can advice CS PhD students? These seem like ECE faculty with no CS affiliation?

**Comment by vgiiscacin** [comment]
They are ECE/EE/CDS/ESE faculty without affiliation to the CS Department. However, all of the faculty proposed for addition work in areas such as machine learning, computer vision, communication networks, complex networks including social networks, storage systems, algorithmic game theory, and coding. Students with CS majors apply to ECE/EE/CDS/ESE and can be solely guided by ECE/EE/CDS/ESE faculty in areas such as the above. 

The historical evolution of these departments is the main reason for this phenomenon. For example, most of our faculty members who work in computer vision (and publish at CVPR, ECCV, etc.) are members of the EE department. Likewise, many faculty who work in HPC (and publish in HPDC, SC, etc.) are part of the CDS department. Students with CS majors who have cleared the CS entrance test (GATE) have a choice of applying to three departments for their Ph.D. during admission, based on their areas of interest. There are also joint degree programs offered by two or more departments. For example, the Systems Engineering (also called Systems Science and Automation) masters' program is jointly offered by the EE and CSA departments, and many students who pursue computer vision are part of this program. 

Even though the label "Computer Science" only appears in the title of the CSA department, CS-related activities happen in all the other departments as well. Since the mandate of csrankings.org is to provide guidance to students seeking advanced degrees in CS-related areas, we are proposing to add the faculty members of these other departments who pursue CS-related interests. The faculty proposed for addition are an integral part of the CS activities of the institute, and we would like their work to count towards our Institute's rankings. 

-Vinod Ganapathy.

**Comment by emeryberger** [comment]
The inclusion criteria are pretty clear. They need to be able to solely advise a PhD student _in the CS department or similar_. ECE is not included automatically. Please clarify.

**Comment by vgiiscacin** [comment]
Emery,

Thanks for your response.

According to those criteria, they cannot be included. However, I'd like to request that crankings.org evolve to consider a broader set of criteria for inclusion here, one that takes Institute-specific considerations into account. All our vision faculty are in the EE department, for instance, and as a result all the activity in our institute in that area is not accounted for here at all. There is also substantial CS related work in our Computational and Data Sciences department. Same issue there.

Vinod Ganapathy

**Comment by vgiiscacin** [comment]
Emery,

Could the faculty in our Computational and Data Science department (CDS) be included? I mean, does CDS fall under "or similar" in the inclusion criteria?

Vinod Ganapathy

**Comment by emeryberger** [comment]
It's called CSrankings because it's for people who are looking at CS programs. Faculty members who can solely advise PhD students for a degree in CS (or the equivalent) are welcome. Faculty who happen to publish in included venues but are not able to supervise CS students are not.

**Comment by emeryberger** [comment]
The "or similar" means things like local names for computer science, or recognized subcategories of computer science. A rule of thumb is if there is already a Department of Computer Science, then the faculty members must be able to supervise a PhD student for a PhD from that department.

**Comment by vgiiscacin** [comment]
Ok, thank you. I'll close the pull request then.

**Comment by rangwani-harsh** [comment]
I think CDS-CS has areas of research which all fall under broad CS subcategory. Can @emeryberger you take a look here http://cds.iisc.ac.in/academics/degree-programs/. The PhD degree is awarded in Computer and Data Systems.

**Comment by val-admin** [comment]
@emeryberger, check out the publication pages of the following CDS labs : 

https://val.cds.iisc.ac.in/publications.html#conferences
https://visual-computing.in/publications/
https://dream-lab.in/publication/
http://cds.iisc.ac.in/faculty/vss/publications.htm

All these CDS faculty look for CS students for research and are not affiliated with the CSA department. We are guiding many CS research students toward their Master's and Ph.D. degrees.  This clearly fits your inclusion criterion "Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department." 

After all, CSRanking aims to help CS students find the correct lab/advisor. Adding CDS faculty members who pursue CS-related research will help CS students find the right lab to work in.

**Pull request closed without merging**
