### PR TITLE
Update faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by adamdoupe**
Added Yan Shoshitaishvili (new Assistant Professor) to ASU faculty.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please add a link to home page (`homepages.csv`) & Google scholar (`scholar.csv`). Thanks.

**Comment by adamdoupe** [comment]
@emeryberger Updated `homepages.csv` and `scholar.csv`!

**Comment by emeryberger** [comment]
The official ASU page does not appear to be updated (I was hoping for a departmental web page in your commit; alas...). Please get them to fix this and I will merge.

https://cidse.engineering.asu.edu/facultyandresearch/directory/faculty/

**Comment by emeryberger** [comment]
Found him here: http://sefcom.asu.edu/people.html

**Pull request merged**
