### PR TITLE
Add University of Liverpool faculty

### PR DESCRIPTION
**Pull request by VishalWilde**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Added 21 faculty from the University of Liverpool and updated one Google Scholar page (through editing the attached CSrankings.txt file).** 

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

**Added the following faculty from the University of Liverpool (by editing the attached csrankings.txt file and including the names as they are on DBLP with disambiguation suffixes where applicable):** Note also that I had initially saved as a .rtf file before converting to a .txt file post-edit so not sure if that will be an issue. 

[csrankings.txt](https://github.com/emeryberger/CSrankings/files/4208318/csrankings.txt)

Terry Payne
John Fearnley
Louise Dennis
Thanh-Toan Do
Aris Filos-Ratsikas
Rasmus Ibsen-Jensen
Christian Ikenmeyer
Louwe Kuijer
Xiaowei Huang
David Jackson
Shan Luo
Shagufta Scanlon
Alkmini Sgouritsa
Stuart Thomason
Patrick Totzke
Konstantinos Tsakalidis
Sebastian Wild
Martin Zimmerman
Victor Zamaraev
Jeyarajan Thiyagalingam
Angrosh Mandya

Also updated Google Scholar page of Valentina Tamma.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Just give me a list of the lines in your .csv corresponding to the Liverpool faculty and I will merge them manually.

**Comment by VishalWilde** [comment]
Okay, apologies for any inconvenience caused. Please do let me know what I can do to make things easier / more efficient in future. List as follows (also, the text editor took the liberty of adding backslashes at the end of each line after a saving as so not sure if that made a difference):

Terry R. Payne,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/terry-payne/,MrkZ_v0AAAAJ&hl=en\

John Fearnley,University of Liverpool,https://cgi.csc.liv.ac.uk/~john/,EmxapaUAAAAJ\

Louise A. Dennis,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/louise-dennis/,5d8ouI8AAAAJ\

Thanh-Toan Do,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/thanh-toan-do/,nihSW_QAAAAJ\

Aris Filos-Ratsikas,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/aris-filos-ratsikas/publications/,iaxTRPoAAAAJ\

Rasmus Ibsen-Jensen,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/rasmus-ibsen-jensen/,NVTh2QgAAAAJ\

Christian Ikenmeyer,University of Liverpool,http://pcwww.liv.ac.uk/~iken/,"NOSCHOLARPAGE"\

Louwe B. Kuijer,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/louwe-kuijer/,iF9PsigAAAAJ\

Xiaowei Huang,University of Liverpool,https://cgi.csc.liv.ac.uk/~xiaowei/,X4fLCCIAAAAJ\

David Jackson 0001,University of Liverpool,https://cgi.csc.liv.ac.uk/~dave/,"NOSCHOLARPAGE"\

Shan Luo,University of Liverpool,https://cgi.csc.liv.ac.uk/~shanluo/,ArnkrbwAAAAJ\

Shagufta Scanlon,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/shagufta-scanlon/,"NOSCHOLARPAGE"\

Alkmini Sgouritsa,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/alkmini-sgouritsa/,Mb_AoIgAAAAJ\

Stuart Thomason,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/stuart-thomason/,"NOSCHOLARPAGE"\

Patrick Totzke,University of Liverpool,https://cgi.csc.liv.ac.uk/~patrick/,ck8G3CgAAAAJ\

Konstantinos Tsakalidis,University of Liverpool,https://cgi.csc.liv.ac.uk/~tsakalid/,ijD-PSQAAAAJ\

Sebastian Wild,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/sebastian-wild/publications/,aMyZiK0AAAAJ\

Martin Zimmerman 0002,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/martin-zimmermann/,ZcmrhggAAAAJ\

Victor Zamaraev,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/viktor-zamaraev/,HpS4Y2wAAAAJ\

Jeyarajan Thiyagalingam,University of Liverpool,https://www.liverpool.ac.uk/electrical-engineering-and-electronics/staff/jeyan-thiyagalingam/,qe4dPiwAAAAJ\

Angrosh Mandya,University of Liverpool,https://www.liverpool.ac.uk/computer-science/staff/angrosh-mandya/publications/,V2IwYWQAAAAJ\

Updated Google scholar entry for the following:

Valentina A. M. Tamma,University of Liverpool,http://www.csc.liv.ac.uk/~valli,tYimqvsAAAAJ\

**Comment by emeryberger** [comment]
Merging these manually. I trust this is the last major change, but in any event, the workflow is that you fork the repo, you modify `csrankings.csv`, and then you issue a pull request.

**Comment by emeryberger** [comment]
Updated.

**Comment by VishalWilde** [comment]
Thank you. I only have one major change to make (not right away but maybe later this month) to add some Electrical Engineering and CompBio/Bioinformatics faculty (those whose research footprints are at least partially capture by DBLP). Will try doing as you’ve said for that.

**Comment by emeryberger** [comment]
Ok, but note that non CS faculty do not by default become eligible for inclusion simply by virtue of publishing in DBLP or even in CSrankings venues. Please read the inclusion criteria above. Thanks.

**Comment by VishalWilde** [comment]
Okay, thank you. I’ve now made the fork and opened / closed the pull
request that references it.

**Pull request closed without merging**
