### PR TITLE
updated sutd faculty

### PR DESCRIPTION
**Pull request by hlseah**
Redo the pull and upload steps. Hope there is no more conflict.
This is to update SUTD faculty profile in the CSranking file.

### CODE REVIEW

**Comment by emeryberger** [comment]
Lots of conflicts, probably with line endings. :(

**Comment by hlseah** [comment]
Hi,

I am not sure what causes the conflict as I merely added a few new rows (comprises of four fields each) into the file using an editor.
Can someone advise me or is it possible for you to assist me with adding the new entries for our faculty?

Shall look forward to hear from you.

Regards,
Hou Liang

**Comment by emeryberger** [comment]
Post the changed csv lines here (in a comment) and I will enter them manually.

**Comment by hlseah** [comment]
Dear Emery Berger,

Please find the seven rows of entries for update in the CSrankings file below as well as the attachment.

Christopher M. Poskitt   SUTD     http://chrisposkitt.com/                                                                               W6er5NgAAAAJ
Ioannis Panageas             SUTD     https://panageas.github.io/                                                                        5NiFWuwAAAAJ
Kai Fong Ernest Chong   SUTD     https://people.sutd.edu.sg/~ernest_chong/                                        JewaBYEAAAAJ
Kwan Hui Lim                     SUTD     https://sites.google.com/site/limkwanhui/                                          K3oGQ4QAAAAJ
Pawel Szalachowski         SUTD     https://pszal.github.io/                                                                                 kbU4kW8AAAAJ
Simon T. Perrault             SUTD     https://istd.sutd.edu.sg/people/faculty/simon-perrault                  pfKzDx8AAAAJ
Tien Tuan Anh Dinh         SUTD     https://istd.sutd.edu.sg/people/faculty/dinh-tien-tuan-anh         224X-HoAAAAJ

Appreciate your help to look into this matter.

Thank you,
Hou Liang

**Comment by hlseah** [comment]
Hi,

May I know if you have completed the manual updates for our faculty below?

Regards,
Hou Liang

From: Seah Hou Liang
Sent: Tuesday, 21 May 2019 9:00 AM
To: emeryberger/CSrankings <reply@reply.github.com>; emeryberger/CSrankings <CSrankings@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [emeryberger/CSrankings] updated sutd faculty (#1507)

Dear Emery Berger,

Please find the seven rows of entries for update in the CSrankings file below as well as the attachment.

Christopher M. Poskitt   SUTD     http://chrisposkitt.com/                                                                               W6er5NgAAAAJ
Ioannis Panageas             SUTD     https://panageas.github.io/                                                                        5NiFWuwAAAAJ
Kai Fong Ernest Chong   SUTD     https://people.sutd.edu.sg/~ernest_chong/                                        JewaBYEAAAAJ
Kwan Hui Lim                     SUTD     https://sites.google.com/site/limkwanhui/                                          K3oGQ4QAAAAJ
Pawel Szalachowski         SUTD     https://pszal.github.io/                                                                                 kbU4kW8AAAAJ
Simon T. Perrault             SUTD     https://istd.sutd.edu.sg/people/faculty/simon-perrault                  pfKzDx8AAAAJ
Tien Tuan Anh Dinh         SUTD     https://istd.sutd.edu.sg/people/faculty/dinh-tien-tuan-anh         224X-HoAAAAJ

Appreciate your help to look into this matter.

Thank you,
Hou Liang

**Comment by emeryberger** [comment]
I have not - can you please go ahead and comma separate the fields so I can simply copy and paste them in? Thanks.

**Comment by hlseah** [comment]
Dear Emery Berger,

OK, please find enclosed updated file with comma separators. Appreciate your assistance on this matter.
Shall hear from you soon.

Regards,
Hou Liang

**Comment by emeryberger** [comment]
Manually added.

**Comment by hlseah** [comment]
Thank you.

**Pull request closed without merging**
