### PR TITLE
added UH faculty members

### PR DESCRIPTION
**Pull request by alipourm**

### CODE REVIEW

**Review by emeryberger — CHANGES_REQUESTED** [review]
Please remove double spaces between first and last names and the special character after the last entry.

**Review by emeryberger — APPROVED** [review]

**Comment by emeryberger** [comment]
Thanks!

**Comment by emeryberger** [comment]
Please check over the automatically generated home pages (`homepages.csv`) and submit a PR to fix anything that needs fixing.

**Comment by alipourm** [comment]
Thanks! URLs seem fine to me.

**Pull request merged**
