### PR TITLE
add Institute of Information Engineering，Chinese Academy of Sciences …

### PR DESCRIPTION
**Pull request by 12281001**
…again

Thanks for your reply, I am sorry that I did't to reply you, because I didn't know how to fix. But now I use vi to edit the file "country-info.csv" and the file "csrankings.csv”. I hope it can be accepted.
And here is website: http://dblp.org/pers/hd/c/Chen_0012:Kai

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi. See this item from the checklist.

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

**Comment by 12281001** [comment]
Thanks for your remind, but I only know the information of my teacher. Is there any other way I can solve it?
Thank you very much!

**Comment by emeryberger** [comment]
You need to look up all the other information before I can accept this PR (which now conflicts).

**Comment by 12281001** [comment]
Thanks for your reply, my teacher offer a list of faculty, and I am writing the information of other teachers, I will pull request again after I finish.
BTW, why there is a remind that the country-info.csv? what does this mean? Can you help me?
Thank you very much

**Comment by 12281001** [comment]
Hi,
I finished writing the information of other teachers, and I have pulled request again, please accept this PR.
If there is any mistakes, please tell me how to fix, I need your help
Thank you very much.

**Comment by xiongyingfei** [comment]
It seems that this pull request contains only 11 professors. I performed a simple googling and found that there should be more people: http://www.iie.cas.cn/yjsjy_101173/dsyd/201707/t20170712_4832169.html

**Comment by emeryberger** [comment]
@xiongyingfei - the English translation via Google says "researcher" and "associate researcher" for many people listed on that site, and only very few are listed as "professor".

**Comment by xiongyingfei** [comment]
The third column explains whether this person can advise Ph.D. students or master students, and many of them advise Ph.D. students. Since this is an independent research institute rather a university, they only have assistant/associate/full researcher rank rather than professors. All professors listed in this table are actually guest professors and should not be included.

Of course, whether independent research institutes should be included is another issue. So far csrankings.org does not have research institutes such as MPI, INRIA, Microsoft Research, etc.

**Comment by 12281001** [comment]
Here is the list( [http://scs.ucas.ac.cn/index.php/zh-cn/szdw/gangweijiaoshi](http://scs.ucas.ac.cn/index.php/zh-cn/szdw/gangweijiaoshi) ), but many of them are not in dplp. I just found  11 professors had their information in dplp.

**Pull request closed without merging**
