### PR TITLE
Add professors in Chinese Academy of Sciences

### PR DESCRIPTION
**Pull request by wentaozhu**
Add professors in Chinese Academy of Sciences

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
I'd highlight that many of these faculty are from the [Institute for Automation](https://en.wikipedia.org/wiki/Institute_of_Automation,_Chinese_Academy_of_Sciences), which seems as independent as the **Information Engineering** Departments in [Oxford](http://www.robots.ox.ac.uk/), [Cambridge](http://www.eng.cam.ac.uk/research/academic-divisions/information-engineering) or [Chinese University of Hong Kong](http://www.ie.cuhk.edu.hk/main/index.shtml), or even **Informatics** at [TU Munich](https://www.in.tum.de/en/research/research-cluster/). Related to #604  and #480 .

**Comment by emeryberger** [comment]
Ah - good catch, @fycus-tree. Please clarify, @wentaozhu .

**Comment by wentaozhu** [comment]
@fycus-tree Due to historical reasons, a big percentage of professors in Institute of Automation, Chinese Academy of Sciences are working on computer science related research, and they are professors advising computer science PhD students. Sure. There are still some professors in the institute working on control related research. These professors are in the computer science department and control department respectively according to their research areas. The professors I listed all have computer science PhD students to advise.

**Comment by fycus-tree** [comment]
@wentaozhu I guess, by what definition are they "Computer Science" students? The Robotics group in #604 is run by [Andrew Zisserman](https://en.wikipedia.org/wiki/Andrew_Zisserman) which wikipedia describes as a famous computer scientist, but that department is not currently included. Presumably because Oxford also has a Computer Science department (which doesn't study machine learning or robotics). In your case, there is also a [Institute for Computing](http://english.ict.cas.cn/) and [Institute of Software](http://english.is.cas.cn/), which seem a better fit than the [Institute of Automation](http://english.ia.cas.cn). The first IA faculty I checked in your list, [Chengqing Zong](http://nlpr-web.ia.ac.cn/cip/english/zong.htm#1.%C2%A0%C2%A0EDUCATION:_0) states his education as "Ph.D. in Computer Science and Application, Institute of Computing Technology, Chinese Academy of Sciences", which lends credence to the idea that the idea that IA isn't the "computer science department" equivalent. Also, all the highest publishing members of the CAS are in the ICT, not the IA. Can IA members supervise ICT students? Because [ICT](http://www.ict.cas.cn/yjsjy/gk/) seems like the institute most closely matching "Computer Science" 

Despite the above, it's also not clear to me that the Chinese Academy of Sciences isn't like #674 or the [Max Plank Institutes](https://en.wikipedia.org/wiki/List_of_Max_Planck_Institutes). Many of the authors on papers seem affiliated with the [University of Chinese Academy of Sciences](http://english.ucas.ac.cn/), which has a, perhaps, [appropriate department](http://scce.ucas.ac.cn/index.php/en/about-us).

**Comment by wentaozhu** [comment]
Dear @fycus-tree ,

I am very sorry for the mis-understanding. Three years ago I obtained my master degree from the university of Chinese Academy of Sciences. 

Like many universities, for students, we get the degree from the University of Chinese Academy of Sciences. And the professors in these institutes recruit or advise students only from University of Chinese Academy of Sciences. We have school of computer and control engineering (full list schools in http://english.ucas.ac.cn/index.php/academics/schools-colleges). And I know the computer science major or department being in the school because I got my computer science master degree there. For the professors I added, they are all in the computer and control engineering school and their research interests are all computer science (advising computer science PhD students now), which you can find in http://scce.ucas.ac.cn/index.php/zh-CN/szdw/gwjs (note: do not go to English version because there is little information). 

There are a lot of mis-understandings because the Chinese Academy of Sciences is a very conservative place (also many highest honors) previously. But it will become better and better since it aims to build a world-class university in its recent goal.

You can also find more information in #759 

Thank you very much for your interest in the Chinese Academy of Sciences and have a great day!

Wentao

**Comment by fycus-tree** [comment]
@wentaozhu Thanks for the clarification. So I guess the University is the "University of Chinese Academy of Sciences" and the department is the "School of Computer and Control Engineering". But then specific professors have primarily affiliations with Institutes, which are not degree granting, but they advise/recruit students from the University. Even though some graduates list their Institute as the source of the degree, that may simply be shorthand. 

I understand that university systems vary greatly in some countries. My own opinion is that CSRankings should allow all professors, regardless of department affiliation, into the fold, as long as they advise PhD students and are primarily affiliated with said University. I personally don't mind if the professor's appointment is in CS, EE, or even English. With the current ranking criteria, there's no harm in extra faculty, and as you're only rewarded credit for actually publishing in top-tier CS venues, it still ranks correctly for the field of CS. But that's not the current criteria, and I'm always happy to get more information about this topic. But that's a topic for #480 

Thanks again

**Comment by wentaozhu** [comment]
Dear @fycus-tree ,

Exactly. I only added the professors in the computer science department that advise computer science PhD students in the department rigorously. And Thank you very much for your interest on Chinese Academy of Sciences!

I am sorry that I do not know how to handle your concerns. I am a PhD candidate (busy) in UC Irvine now, and found that there is very few professors in the Chinese Academy of Sciences. That is the reason for my PRs.

Wentao

**Pull request merged**
