### PR TITLE
Update venues.csv

### PR DESCRIPTION
**Pull request by kimns516**
HPCA is suggested in arch category

### CODE REVIEW

**Comment by emeryberger** [comment]
Not changing. The venues for the architecture conferences were selected after surveying key members of the architecture community.

**Comment by kimns516** [comment]
Dear Emery

I dont know who those key members are but i think that's very controversial
and subjective if the list is selected by a few folks because many will not
see asplos as a hardcore arch conference (i am not saying it's not worthy)
and i know that  many will consider hpca as one of top 3 arch confetences
and many highly recognised comp arch folks will agree with that. If needed
I can ask those folks and get their endorsement as well.

Nam Sung Kim
Professor
IEEE Fellow
Dept of Electrical and Computer Engineering
University of Illinois, Urbana Campaign


On Sep 17, 2017 8:29 PM, "Emery Berger" <notifications@github.com> wrote:

Not changing. The venues for the architecture conferences were selected
after surveying key members of the architecture community.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/emeryberger/CSrankings/pull/451#issuecomment-330105212>,
or mute the thread

**Comment by emeryberger** [comment]
To be more clear: this was the result of a survey sent directly to the entire 2017 ISCA program committee, which comprised many highly recognized computer architects (naturally). The top three conferences were ISCA, MICRO, and ASPLOS; HPCA was fourth.

**Comment by emeryberger** [comment]
That said, the current 3 conference limit is not set in stone. If this policy changes, HPCA would likely be added to the list.

**Comment by kimns516** [comment]
Thank you for the clarification. I was a 2017 ISCA TPC member and
discussing your reply with another respected computer arch who was also an
ISCA 2017 TPC member. We do remember a surNeither of us  remember about
 the survey

**Comment by kimns516** [comment]
I am sorry i sent a click button instead of cancel button on incompleted
email written using a phone. The point was I was one of  2017 ISCA members
and me and another ISCA TPC member whom I discussed your previous email
with dont remember that specific part although we do remember a long survey
on how to improve the review process.

The following was from the other person who is now 2018 HPCA chair.
"
interesting, I guess they only asked SIGARCH folks? I believe HPCA is the
flagship conference for IEEE TCCA, but SIGDA doesn't own it."

Anyway thank you for your effort to build such a nice site and kind
responses for my emails.

One quick suggestion is to consider citations. It wasn't clear whether that
was the case.


Nam Sung

**Comment by emeryberger** [comment]
Hi,

Thanks for the kind words.

I just checked and your email (a gmail address) was among the recipients of the message I sent (sent February 22, 2017), though of course it could have ended up in a spam filter.

The [FAQ](http://csrankings.org/faq.html) has an extensive discussion of methodological questions, including the question of citations.

best,
-- Emery

**Pull request closed without merging**
