### PR TITLE
TTIC

### PR DESCRIPTION
**Pull request by brendano**
This is intended to be a listing of all TT faculty from http://www.ttic.edu/faculty.php; specifically it's all with a {Asst,Assoc,} Professor title.

Note only a few of the TTIC faculty are listed under UChicago's CS dept website.  (I guess this PR would cause those those ones to appear under both institutions in the interface; is that a problem?)  The PhD program is separate (http://www.ttic.edu/phd-program.php).

### CODE REVIEW

**Comment by emeryberger** [comment]
Yeah, we can't currently have duplicates. Can you remove those and make a separate PR for those?

**Comment by brendano** [comment]
yikes it's a lot of people who are listed under both

```
Greg Shakhnarovich
Jinbo Xu
Julia Chuzhoy
Madhur Tulsiani
Karen Livescu
```

**Comment by emeryberger** [comment]
Curious what this means...

**We at TTIC continue to admit students to our PhD program. Please contact me for details.** 

(from http://ttic.uchicago.edu/~gregory/)

**Comment by emeryberger** [comment]
In any event, it looks like that in at least most cases the primary affiliations are TTI and not UChicago (see "part-time").

https://www.cs.uchicago.edu/directories/table/faculty

**Pull request merged**
