### PR TITLE
Fix Dan Goldwasser broken homepage link

### PR DESCRIPTION
**Pull request by MSheshera**
Change homepage link from http://dan-goldwasser.com/ (which links to a very random page) to https://www.cs.purdue.edu/homes/dgoldwas/ which is linked to from the Purdue CS [website](https://www.cs.purdue.edu/people/faculty/dgoldwas/).

### CODE REVIEW

**Comment by emeryberger** [comment]
Many of these pages were generated automatically (via Google-fu), and it's not a perfect solution. Thanks for the update!

**Comment by MSheshera** [comment]
You're welcome! Is it happening here: https://github.com/emeryberger/CSrankings/blob/gh-pages/util/make-web-pages.py? I could try to make it do better somehow if you think its worth it.

**Comment by emeryberger** [comment]
That's the one. If you have suggestions (or better yet, code) to make it better, that would be great!

**Comment by MSheshera** [comment]
Neither as of now, but I'll certainly take a look and get back on this!

**Pull request merged**
