### PR TITLE
Added professors in CUHK and USYD working on computer vision

### PR DESCRIPTION
**Pull request by kevin-ssy**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
I would say that this is a somewhat problematic commit given the current standards for inclusion. See #480 and #604. I checked a few of these out and.. for example.. all the CUHK folks are in [Information Engineering](http://www.ie.cuhk.edu.hk/people/people.shtml), not [Computer Science](http://www.cse.cuhk.edu.hk/v7/en/people/lec.html). If they get accepted, so should most of the folks from #604.

**Comment by kevin-ssy** [comment]
That's true, all these professors are from the dept of IE rather than CS. However, their research field is highly related to computer vision, machine learning, and pattern recognition. There are many students majoring in CS also applying for and working in their lab. Meanwhile, the research topics of all these professors are also set in the dept of CS. In my opinion, the CSRanking now is ranked according to the research field instead of department. Especially, the professor Xiaoou Tang and Xiaogang Wang are quite well-known in the field of computer vision, it is very weird to remove them from the list simply by the reason of dept.

**Comment by fycus-tree** [comment]
@kevin-ssy I understand where you're coming from.

If you look at #604, [Andrew Zisserman](https://en.wikipedia.org/wiki/Andrew_Zisserman) is still "proposed for inclusion" for the same reason (which is proposing adding IE faculty from Oxford); feel free to read my comments in that thread for what I think should be done. However, Emery has pointed folks towards #480 to discuss this topic further. 

In his words from #604, 
> faculty who are able to singly advise PhD students in Computer Science meet the inclusion criteria. Faculty in Engineering departments and the like are not automatically eligible for inclusion, regardless of the topics on which they publish.

**Comment by emeryberger** [comment]
Closing since these faculty do not meet the current inclusion criteria.

**Pull request closed without merging**
