### PR TITLE
Add POMACS (=SIGMETRICS) to Measurements & performance analysis

### PR DESCRIPTION
**Pull request by thang-dinh**
Starting 2017, Sigmetrics papers will be published in Proceedings of the ACM Series on Computing Systems Modeling, Measurement and Evaluation (POMACS). 

Call for paper from Sigmetrics'17 (the end of the 2nd paragraph)
[https://www.sigmetrics.org/sigmetrics2017/Call%20for%20Papers.html
](https://www.sigmetrics.org/sigmetrics2017/Call%20for%20Papers.html)

Links to POMACS:
[http://pomacs.acm.org/](http://pomacs.acm.org/)

### CODE REVIEW

**Comment by emeryberger** [comment]
It looks like POMACS plans to incorporate not just SIGMETRICS but other conferences; correct? If so, I will need to know how they plan to distinguish SIGMETRICS papers from others.

**Comment by thang-dinh** [comment]
I'm not aware of any plan to incorporate other conferences to POMACS. The pair POMACS-Sigmetrics is pretty much like IMWUT-Ubicomp. At least 'til the end of 2018, POMACS will only publish papers from Sigmetrics.

**Comment by emeryberger** [comment]
Right, though IMWUT has already made clear it plans to include other conferences. Anyway, will add for now. I'd appreciate it if you could notify me when and if other conferences are included.

**Comment by thang-dinh** [comment]
Thanks! I'll monitor for publication of other confs in the journal.

**Pull request merged**
