### PR TITLE
Update mcmaster university affiliations.

### PR DESCRIPTION
**Pull request by shervinmanzuri**
Added Dr. Richard F. Paige to the list of mcmaster university faculty.

### CODE REVIEW

**Comment by emeryberger** [comment]
Web page says that he maintains a part-time appointment at York. Is the McMaster position full time?

**Comment by shervinmanzuri** [comment]
> Web page says that he maintains a part-time appointment at York. Is the McMaster position full time?

To the best of my knowledge he is currently appointed as a full professor of SE at mac and looking for prospective PhD students at McMaster.

**Comment by emeryberger** [comment]
Please ask him to clarify via a comment here.

**Comment by emeryberger** [comment]
Closing due to lack of response.

**Pull request closed without merging**
