### PR TITLE
Mälardalen University added

### PR DESCRIPTION
**Pull request by Aeoliphile**
Mälardalen University added, with the complete list of eligible professors

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

0. Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv"). **IF YOU DO NOT DO THIS, YOUR COMMIT WILL BE SUMMARILY REJECTED.**

1. _Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

2. _Insert new faculty **in alphabetical order**, not at the end of `csrankings-[a-z].csv`._ **Do not modify `csrankings.csv`, which is auto-generated.** **DO NOT MODIFY `csrankings-[0-9].csv`, WHICH ARE BEING DEPRECATED. USE `csrankings-[a-z].csv` INSTEAD.**

3. _Read and check **all** the boxes below by filling them in with an X._

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**; please **do not** use the numeric suffixes, which are being obsoleted); include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

**(Advanced) Quick contribution via a shallow clone** 

A full clone of the CSrankings repository is almost 2GB.  To contribute a change without creating a full local clone of the CSrankings repo, you can do a _shallow clone_.  To do so, follow these steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)
2. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.
3. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to do another contribution and some time has passed, perform steps 1-3 again, creating a fresh fork and shallow clone.

### CODE REVIEW

**Comment by Aeoliphile** [comment]
Dear professor Emery,

I did as you requested. Here is the single pull request, consisting of all the necessary edits for adding the Mälardalen University with its eligible faculty members.

**Comment by emeryberger** [comment]
A quick spot check turned up a number of faculty who are not in Computer Science (e.g., in ECE). Unless they have a joint appointment and can _solely_ advise PhD students _in Computer Science_, they are not eligible for inclusion here. I would expect all eligible faculty to appear [on this list.](https://www.es.mdh.se/divisions/53-Division_of_Computer_Science_and_Software_Engineering). Please remove all ineligible faculty and re-open.

**Comment by Aeoliphile** [comment]
Dear professor @emeryberger ,

At MDU, the naming convention of different departments does not imply that one professor cannot supervise a PhD student in Computer Science. At MDU, we for example have NES (Networked and Embedded Systems), IFT (Intelligent Future Technology), and CSE (Computer Science and Software Engineering). All three are working on different aspects of computer science, and there is a PhD program in computer science to which all divisions contribute to. 

To the best of my knowledge, all included professors can solely advise PhD students in Computer science, and all of them have publications in CS conferences and journals. For example, some of the professors belonging to NES and IFT departments, are still publishing at RTAS, RTSS, and EMSOFT, which are the conferences recognised by CSrankings. The students still obtain the degree "PhD in Computer Science with specialisation in embedded and networked systems", or similar.

Is not this enough to be included in your ranking?

**Comment by emeryberger** [comment]
Publication venues are immaterial - the issue is the degree and sole supervision capacity. As long as they can solely supervise a PhD in CS, they are eligible for inclusion.

**Pull request merged**
