### PR TITLE
Update faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by pdruschel**
Added MPI full-time, tenure-track faculty

### CODE REVIEW

**Comment by pdruschel** [comment]
Reopening pull request... see comment above.

**Comment by emeryberger** [comment]
@pdruschel, thanks for the PR. Merged and updated (also had to add to `country-info.csv`, which I have done). Please verify that the automatically generated `homepages.csv` file is correct.

**Comment by pdruschel** [comment]
Thanks, Emery.

The homepages.csv entries look good, except the following is a better 
link for Gene Myers:

https://www.mpi-cbg.de/research-groups/current-groups/gene-myers/group-leader/

Also, I noticed that of the 23 faculty I entered, only 18 seem to show up.

Stefan Schaal and Joel Ouaknine seems to still be listed under their 
previous affiliations (USC and Oxford, respectively). Do they have to 
submit individual change requests?

Deepak Garg seems to be missing entirely. Given that there are several 
people by that name, should I enter him as "Deepak Garg 0001", which 
seems to be how he goes in DBLP?

Gene Myers and Martin Vingron appear to be missing for unknown reasons.

Best,

   -- Peter

PS: Thanks for putting together this fantastic site!

**Comment by emeryberger** [comment]
I have updated the affiliations for Schaal and Ouaknine. The others are not yet listed because I have yet to include computational biology / bioinformatics; this is likely to be added in the near future.

**Comment by pdruschel** [comment]
Thanks a ton, Emery.

I imagine you get a lot of suggestions for additional areas and 
conferences to add. For what's its worth, I am passing along some 
requests from my colleagues, which seem reasonable to me:

CSF and NDSS should be added to security.

ICFP and ESOP should be added to programming languages.

Real-time systems: RTSS, RTS, RTAS

Social computing/Computational social science: ICWSM, WSDM and CSCW

Thanks,

   -- Peter

**Comment by emeryberger** [comment]
No problem, Peter. Thanks for the updates.

There is currently a limit of three conferences per area. The criterion for inclusion is that they must all be in the same equivalence class in terms of selectivity (acceptance rates) and sizes; most of the conferences suggested would not meet that bar (with the notable exception of NDSS).

Areas are generally included because they are represented by an ACM SIG. Including other areas is planned (and several are already present: vision, robotics, and NLP) but requires that at least 50 R1 institutions have published in that area since 2000. This info is at the bottom of the page but probably needs to be put into a FAQ...

**Pull request merged**
