### PR TITLE
Add Zhejiang University

### PR DESCRIPTION
**Pull request by crcrcry**
Zhejiang University is one of the top universities in China. We want to add it to CSrankings.

### CODE REVIEW

**Comment by emeryberger** [comment]
You have accidentally changed formatting for your commits (possibly because it is in DOS CR/LF format), making it impossible for me to review the diffs. There are also some spurious characters (look for Queen's University in `country-info.csv`). Please switch to a Unix format (on many platforms, you can do this by running `dos2unix`) and re-commit. Thanks.

**Review by emeryberger — COMMENTED** [review]
Why was this code committed? What is it intended to do?

**Comment by crcrcry** [comment]
I am sorry about the code, I commit it in error.

**Comment by crcrcry** [comment]
Thanks for your guidance.  I am very sorry for the trouble.

**Comment by emeryberger** [comment]
This is a very large commit, and I don't think it follows the established procedure. In particular, I don't see a single disambiguation entry, which is very unlikely to be correct. I picked one random example, Jian Chen, and the correct entry is "Jian Chen 0009". See http://dblp.uni-trier.de/pers/hd/c/Chen:Jian.

Please follow the steps here: https://github.com/emeryberger/CSrankings/blob/gh-pages/docs/CONTRIBUTING.md

**Comment by crcrcry** [comment]
Sorry to have caused you so much trouble before.

**Comment by emeryberger** [comment]
Thanks!

**Pull request merged**
