### PR TITLE
add Tsinghua University with a few faculty

### PR DESCRIPTION
**Pull request by shuaimu**

### CODE REVIEW

**Comment by emeryberger** [comment]
I assume there are many more faculty in CS at Tsinghua - are you planning to add them in a subsequent commit? I'd rather take one full PR with everyone.

**Comment by shuaimu** [comment]
Not really:) Those are all I am familiar with. Though I can broadcast an email to the dudes in Tsinghua I know to encourage them to add more entries.

**Comment by shuaimu** [comment]
FYI The most recent commit is to separate NYU Tandon (previously Poly) from NYU. Tandon is an independent school with different management and admission system. It is to NYU as NYU Shanghai is.

**Comment by emeryberger** [comment]
NYU is a complicated case. NYU Shanghai is a clearly different campus (to say the least). For now, I am not going to make that kind of change, which in any event **has** to be in a separate PR.

**Pull request closed without merging**
