### PR TITLE
Add DA/SC Research Staff

### PR DESCRIPTION
**Pull request by ahmed451**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Review by ahmed451 — COMMENTED** [review]
I can see the changes been posted. Was the pull got pushed?

**Comment by emeryberger** [comment]
There is still a giant diff - possibly because the line endings have changed - so I cannot audit it.

**Comment by ahmed451** [comment]
1. Regarding Marco, he told me that he supposed to join UMass this Jan. but he postponed it to next fall. So he will be around till Aug. 18. 
2. QCRI is a research institute. Most of its staff are researchers/professors who taught or still teaching and advising students. The institute itself doesn't offer courses. This is similar to Max Planck Institute or IMDEA Software Institute and other institutes listed.

**Comment by emeryberger** [comment]
Yes, the inclusion of these institutes is something that needs to be reconsidered; unless students apply to these institutes for their PhDs, they will likely have to be removed. Can you elaborate on how it works at QCRI?

**Comment by ahmed451** [comment]
QCRI does not grant PhD degrees, but students complete the PhD research requirements at the institute under the supervision or co-supervision of QCRI researchers. This is similar to the case of the Max Plank Institutes, where the PhDs are awarded by the collaborating universities, not by the MPIs. It is crucial for such research institutes to be listed in order to highlight their fair contribution as well as to help their visibility, thus helping them recruit good PhD students.

**Comment by ahmed451** [comment]
Dear Emery, it has been a while and this ticket still open. We would greatly appreciate if you can commit the pull.
Thanks.

**Comment by ahmed451** [comment]
New pull

**Pull request closed without merging**
