### PR TITLE
Removing the adjunct faculties

### PR DESCRIPTION
**Pull request by tongping**
Hi Emery,

I need to remove the adjunct faculties from the list, as requested by my chair. Thanks!

### CODE REVIEW

**Comment by emeryberger** [comment]
If they can advise CS PhD students and are full-time tenure-track faculty, they should be listed. Otherwise, they should not. Please confirm. Also, please update homepages.csv and update the PR. Thanks!

**Comment by tongping** [comment]
Thanks for your advise. Actually, my char would like to remove them now.

**Comment by tongping** [comment]
I have updated  homepages.csv and PR. Thanks!

**Comment by emeryberger** [comment]
I am merging this based on my understanding that these adjuncts _do not_ meet the inclusion criteria. Please confirm.

**Comment by tongping** [comment]
Thanks! That is right.

**Pull request merged**
