### PR TITLE
Create faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by renau**
Missing faculty from the CE department (new hire too)

### CODE REVIEW

**Comment by emeryberger** [comment]
Apologies if I have asked before - are all of these able to advise PhD students in the CS dept.? I didn't see everyone on this page: https://www.soe.ucsc.edu/departments/computer-science/people/faculty

**Comment by renau** [comment]
We are a bit atypical that we have 3 departments: CS CE EE.

  Architecture, VLSI, CAD, storage are in the CE department. CS is more 
PLDI or theoretical. All the MICRO/ASPLOS/ISCA type of authors are in 
CE.

https://www.soe.ucsc.edu/departments/computer-engineering

**Comment by emeryberger** [comment]
Here's the relevant extract from the FAQ. It's a uniform standard applied to every institution.

> What are the criteria for including faculty?
> 
> The criteria for inclusion (which have been refined since CSRankings' inception) are that anyone who is a full-time, tenure-track faculty member on a given campus who can advise PhD students in Computer Science can be included in the database. This approach thus extends the reach of the database to a number of faculty from other departments who have adjunct appointments with a CS department or similar that let them advise CS PhD students.

**Comment by renau** [comment]
At UCCS, CE faculty can advise CS PhD/MS students. We can do that 
without dual appointment.

**Comment by emeryberger** [comment]
OK, perfect. Thanks.

**Pull request merged**
