### PR TITLE
Added ANU.

### PR DESCRIPTION
**Pull request by hosking**
Will start adding other Australasian institutions.

### CODE REVIEW

**Comment by emeryberger** [comment]
Excellent, thanks @hosking !

**Comment by hosking** [comment]
Hi Emery,

Having fun with this.  What are the plans for disambiguating authors more effectively?  Particularly re common (e.g., Chinese) duplicate names?

Cheers,
— Tony

**Comment by hosking** [comment]
In particular, I see that names match as substrings against other names.

For example:

Uwe Zimmer
Uwe Zimmerman

**Comment by emeryberger** [comment]
DBLP nominally has unique names for every author (for Chinese names, this often means followed by a number like 0001). What do you mean by substring matching - in DBLP?

**Comment by hosking** [comment]
Hi Tony,

DBLP has canonical names for most people, suffixing the name string with numerals when necessary.   It should be possible to identify the individuals by this canonical name.   Of course if the data in DBLP is not right, then we can’t do anything, but I think its generally pretty good.

I used that feature of DBLP when I did the automatic conflict detection stuff for PLDI.   I recall there’s an index file with those canonical names in it.  I’ll come and take a look :-)

--Steve

From: Antony Hosking antony.hosking@gmail.com
Date: Wednesday, 17 August 2016 at 3:11 PM
To: Antony Hosking antony.hosking@gmail.com
Cc: emeryberger/CSrankings reply@reply.github.com, Steve Blackburn steve.blackburn@anu.edu.au
Subject: Re: [emeryberger/CSrankings] Added ANU. (#71)

In particular, I see that names match as substrings against other names.

For example:

Uwe Zimmer
Uwe Zimmerman

On 17 Aug 2016, at 3:00 PM, Antony Hosking <antony.hosking@gmail.com<mailto:antony.hosking@gmail.com>> wrote:

Hi Emery,

Having fun with this.  What are the plans for disambiguating authors more effectively?  Particularly re common (e.g., Chinese) duplicate names?

Cheers,
— Tony

On 17 Aug 2016, at 2:02 AM, Emery Berger <notifications@github.com<mailto:notifications@github.com>> wrote:

Excellent, thanks @hoskinghttps://github.com/hosking !

**Comment by hosking** [comment]
Yes, I know about the canonical names and have used them when I could find them.
With respect to string matching, what I refer to is the outcome for some names, such as “Uwe Zimmer”, which when I click through the results to DBLP yields http://dblp.uni-trier.de/search?q=Uwe%20Zimmer but that shows pubs also from Olaf Zimmerman and Uwe Zimmerman.  Are those results being used to compute the pub numbers?

**Comment by emeryberger** [comment]
No, the count is correct. That's just because it's the easiest way to generate a person link for DBLP. I will see if there's a clean way to get directly to the author's page.

**Comment by hosking** [comment]
OK, no problem.
I’ve got UNSW and U Melbourne about to commit too.  Will issue a pull request.

Thanks, T

**Pull request merged**
