### PR TITLE
Add conference 'TACAS' to area 'Logic and verification'

### PR DESCRIPTION
**Pull request by dbeyer**
I contribute this pull request as a member of the steering committee of TACAS.

Reasoning:
- TACAS has a similar h5-index as CAV and LICS (CAV: 38, TACAS: 33, LICS: 31).
- TACAS has a higher impact score than CAV and LICS in guide2research (TACAS:  5.78, CAV: 5.45, LICS:  3.96).

Thus, I request to add TACAS.  The changes are tested locally.

### CODE REVIEW

**Comment by emeryberger** [comment]
Thanks, but this is not how new conferences are added to any area.

**Comment by jpkatoen** [comment]
@emeryberger: Can you explain to us how conferences are added? At the moment this is not clear, and it would be good to have some transparencu about this so that we can -- if possible -- issue a request to add/change conferences.

(Steering Committee Chair TACAS)

**Comment by rance-cleaveland** [comment]
Let me add voice to the request for some transparency on the mechanism for inclusion of conferences in CSrankings.  The process as described in the FAQ -- "consultation with faculty" -- does not give us much to go on.  (TACAS co-founder and Steering Committee member, also CS faculty at UMD College Park)

**Comment by dbeyer** [comment]
@emeryberger According to http://gotorankings.org/, a GOTO ranking has to satisfy (among others) the following requirement:

- Transparent: process and methodologies are entirely transparent

The https://csrankings.org web site states that it is a GOTO ranking.

Could you please shed light on this issue in connection with the questions from @jpkatoen and @rance-cleaveland above?

**Pull request closed without merging**
