### PR TITLE
add CU Boulder faculty

### PR DESCRIPTION
**Pull request by jrmcclurg**

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - Fabio Somenzi and Pavol Cerny are not in a CS department; only CS or joint EECS departments (or equivalent) are included in the database for now.

**Comment by jrmcclurg** [comment]
Hi, This seems like a strange constraint, considering that those two
faculty publish only in CS conferences (CAV, POPL, PLDI, etc.)

**Comment by emeryberger** [comment]
Well, it's a site for ranking CS departments, after all.

**Comment by jrmcclurg** [comment]
Sorry to be pedantic, but that's not what the description on the website seems to indicate. Maybe the description could be edited to be (much) less general?

> This ranking makes it easy to identify **institutions** and **faculty** actively engaged in research in a number of areas of computer science. Unlike US News and World Report's, which is exclusively based on surveys, this ranking is entirely objective. It measures the **number of publications by faculty that have appeared at the most selective conferences** in each area of computer science.

**Comment by emeryberger** [comment]
See issue https://github.com/emeryberger/CSrankings/issues/39.

**Comment by jrmcclurg** [comment]
Thanks!!

**Pull request closed without merging**
