### PR TITLE
Added some missing Cornell faculty that can advise CIS PhD students

### PR DESCRIPTION
**Pull request by thorstenjoachims**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
Can you clarify where Information Science professors can advise Computer Science students? The website says [Students primarily interested in technical foundations should consider Computer Science. ](http://infosci.cornell.edu/academics/phd/phd-frequently-asked-questions)

**Comment by thorstenjoachims** [comment]
We have created CIS (The Faculty of Computing and Information) to contain all areas of computer science and still comply with Cornell's organizational limits (e.g. departments cannot have more than 50 faculty, unlike at other schools). So, areas like HCI, Social Networks, Information Retrieval, and Economics+Computation have moved into Information Science. That explains the sentence you quote, since the CS areas we moved into Information Science are the areas of Computer Science that interface with humans (not just technical in isolation).  

Let me know, if you have any other questions.

**Comment by fycus-tree** [comment]
I'd like to point that this is similar to #604, which has not been accepted for inclusion. There, the Information Engineering department, separate from Computer Science, works on AI, Robotics, etc. but because a separate top-level department exists, it isn't accepted.

**Comment by thorstenjoachims** [comment]
The structure we have here at Cornell is analogous to that at CMU, where there is a top-level entity School/Faculty with different sub-areas of computer science underneath. At CMU this is the Computer Science Department, HCII, Robotics, Machine Learning, etc. I notice that the HCII faculty at CMU are included, which sets a precedent for also including the Cornell HCI faculty.

**Comment by fycus-tree** [comment]
I'd say your analogy is flawed. CMU has a School of Computer Science, with a singular undergraduate degree and several sub-departments for graduate programs; it is a top-level college in the [university](https://www.cmu.edu/academics/index.html), entirely separate from the College of Engineering. Cornell has two separate departments, IS and CS, each with separate undergraduate programs and the ["Faculty in Computer and Information Science"](http://www.cornell.edu/academics/colleges.cfm) is listed as a "Special-Mission Faculty Unit", not as a separate college. IS and CS are both considered departments in the [College of Engineering](https://www.engineering.cornell.edu/programs-departments). Thus I think this is more similar to the situation in #604, where there's Information Engineering and Computer Science as separate departments. 

I'd ask that you post on #480 if you have thoughts on the inclusion criteria in general. 

EDIT: Additionally it seems that CMU allows their SCS PhD students to switch between their [departments](https://www.cs.cmu.edu/doctoral-admissions-frequently-asked-questions) after admission, making their department boundaries moot.

**Comment by thorstenjoachims** [comment]
I maintain that my analogy with CMU is accurate.

First, it is not true that CS and IS at Cornell are in the College of Engineering at Cornell. Both departments are entirely in CIS under Dean Greg Morrisett, who is CC’ed on this email. CIS is a top-level college just as much as the School of Computer Science at CMU is a college.

Second, CMU also offers multiple undergraduate programs. See https://www.cs.cmu.edu/undergraduate-programs.
---
Thorsten Joachims
Chair, Department of Information Science
Professor, Department of Computer Science
Cornell University
http://www.joachims.org/

**Comment by fycus-tree** [comment]
That's not clear from the Cornell Engineering website, which [lists CS and IS as separate departments](https://www.engineering.cornell.edu/programs-departments)  in Engineering, while  CIS is called a [special faculty unit](http://www.cornell.edu/academics/colleges.cfm), not a college. Additionally on the CMU side, you're right, they current have (2), a CS and Comp Bio undergraduate degree, but there's more than half a dozen departments in their School of CS and they mostly don't offer undergraduate degrees; while graduate students are allowed to switch between departments. In Cornell CIS, it seems there's multiple departments, multiple undergraduate programs, and it's not clear that graduate students can switch between them.

**Comment by andrewcmyers** [comment]
One issue that may be confusing here is that CS graduate students at Cornell are part of the CS *field*, which is more than just the CS *department*. Per the CSrankings inclusion criteria, at least some of the people that Thorsten has added are indeed full-time tenure-track faculty who can be the sole graduate advisor to a CS PhD student. I have made a separate pull request (#853) that adds the cases that are completely unambiguous, along with some new members of the CS department (and field).

**Comment by fycus-tree** [comment]
Can you clarify what the difference is between the CS Department and CS Field? Clearly Cornell has some interesting organization structure (and a 50-head department cap?). Based on your experiences, it would be great if you could share your thoughts on the general CS inclusion criteria in #480.

**Comment by fycus-tree** [comment]
Thanks to the clarification in #853, it seems that the valid list is those who are part of the CS field. That list is located [here, under the dropdown for faculty](https://gradschool.cornell.edu/academics/fields-of-study/field/computer-science)

**Comment by andrewcmyers** [comment]
I'm glad you agree that the faculty in the CS field belong on the csrankings list.

However, I agree with Thorsten that Cornell's CIS and CMU's School of Computer Science are roughly equivalent structures. CIS is a college-level entity at Cornell that is administratively and budgetarily separate from the College of Engineering, the College of Arts and Sciences, and the College of Agriculture and Life Sciences, despite offering undergraduate degrees jointly with each of those other units. CIS only fails to be considered a "college" in Cornell because it does not directly admit its own undergraduates — a factor that seems irrelevant to the present discussion.

**Comment by fycus-tree** [comment]
@andrewcmyers This organization structure isn't clear from some of the websites, which list IS & CS as simply [sub-departments in Engineering](https://www.engineering.cornell.edu/programs-departments), IS recommends ["Students primarily interested in technical foundations should consider CS."](http://infosci.cornell.edu/academics/phd/phd-frequently-asked-questions).

On the difference with CMU: The reason the last distinction is important is because CMU allows SCS PhD students [to switch between departments](https://www.cs.cmu.edu/doctoral-admissions-frequently-asked-questions) post-admission, making the distinction between them largely moot. Additionally, CMU does [faculty hiring on the SCS level](https://apply.interfolio.com/45159). That is, when applying to CMU, as either a PhD student or faculty member, CMU SCS is your "basic operating unit."

To really establish equivalence with CMU, I'd have to ask: at Cornell, are PhD students in IS allowed to become CS students without re-applying (and vice-versa)? Do IS and CS have independent hiring practices? I can't find anything about the former, suggesting it's not possible. While for the latter [IS](http://infosci.cornell.edu/careers), [CS](https://www.cs.cornell.edu/information/jobpostings/facultypositionsithaca) seem to have separate hiring pathways. 

As a final note, I'll just say that, on my reading, IS & CS at Cornell are like CS & IE at Oxford or Cambridge (see #604). However, Emery is part of a "College of Information and Computer Sciences" (with a single PhD offering), so I'm sure he has a better understanding of this issue than I do, and I'll probably stop commenting here. In my personal opinion (in detail at #604), I think CS & IS are simply acknowledging the intrinsic & extrinsic research focuses in computing, and they should both be included under the umbrella "computer science", but that's not my call (I'm just a tree!).

**Comment by andrewcmyers** [comment]
The Engineering website you point to is misleading. CS and IS are not part of Engineering. They do offer undergraduate majors for students from the College of Engineering, though, which is no doubt why they are listed on this page. You will also find Computer Science listed on pages from the College of Arts and Sciences: http://as.cornell.edu/majors-minors-and-grad-fields

CS and IS are different departments with different budgets and different hiring lines, but PhD students do occasionally switch between CS and IS. I'm not sure it is an at-will event, but it certainly does not involve a full application process. As IS chair, Thorsten would know more.

**Comment by thorstenjoachims** [comment]
Thank you, Andrew, for clarifying. Yes, we have had students switch from one graduate field to the other in the past. And, yes, CIS is a college level entity with its own dean that oversees both CS and IS. CIS is the budget home for both CS and IS. Faculty hiring lines are managed by CIS, but the CS and IS run their own searches (although reqularly interviewing candidates jointly). CS and IS are housed in the same building, and walking through the building you would not be able to identify a boundary between the departments (e.g. door signs don't list departments). And even though my appointment is 100% in CS, I am obviously eligible to be department chair of IS.

If I understand you correctly, then the key question is whether applying to the HCII PhD Program at CMU is different from applying to the IS PhD Program at Cornell. I would argue that apart from local administrative idiosyncrasies (e.g. the field system at Cornell and the school system at CMU) they are the same in their intention.

**Comment by fycus-tree** [comment]
@thorstenjoachims I'm just a tree who wants all universities to get a fair shake. Emery is the sole individual whose opinion matters. I don't really care about Cornell or CMU, instead I'm interested in helping probe Emery's inclusion criteria. I just want to sure they work for different universities fairly (e.g. This "information"/"informatics" split is very common in Europe, e.g. TUM, Cambridge, Oxford. The entire Chinese Academy of Science's structure really has universities and departments as secondary to research labs as the primary unit). Hopefully these discussions gives Emery a clearer picture, so he either so he reforms the inclusion criteria (#480) or has an easier time making decisions (#850 #808 #670 #604 #584 #574).

**Comment by thorstenjoachims** [comment]
Thanks. If the intent is to measure how productive an institution is at this specified set of CS venues, it is probably easiest to simply aggregate at the level of the institution without trying to tease apart their organizational structures. If institution X pays Y's salary and Y publishes at venue Z, then it counts.

**Comment by fycus-tree** [comment]
@thorstenjoachims My understanding is that that'd be a notable change from the current system. While the blurb on the website says
> This ranking is designed to identify institutions and faculty

the [FAQ](http://csrankings.org/faq.html) says

>  The primary audience of CSRankings is prospective graduate students who are seeking a postgraduate degree in **Computer Science**.

and historically Emery has read that fairly narrowly (see #604), where if _Computer Science_ degree is offered by an institution, that's the degree that's being evaluated. This leads to a _program-level_ inclusion criteria instead of an _institution-level_ inclusion criteria. 

As you point out, sometimes universities have organization structures that offer PhD degrees with additional specificity or some interdisciplinary focus. At some places, due to historical reasons, there are Electrical & Computer Engineering departments who host the research for a CSRankings field. With the "Interdisciplinary" categories, this happens even more, with Biology (Comp Bio), Mechanical Engineering (Robotics), Economics/Business/Operations Research (Econ & Comp), and Art/Design (HCI, Visualization) departments sometimes having the most relevant faculty. Unless those faculty formally have a "Computer Science" affiliation, they tend to be excluded from this list.

**Pull request closed without merging**
