### PR TITLE
Add newly founded CISPA Helmholtz Center i.G. to list

### PR DESCRIPTION
**Pull request by ben-stock**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by ben-stock** [comment]
Just as an info: Mario Fritz is being added to the CISPA Web site now, he just joined. Should be done by Monday evening CET

**Comment by ben-stock** [comment]
See https://cispa.saarland/people/gallery/ for the complete list now.

Should I resolve the conflicts first and re-open another issue?

**Comment by emeryberger** [comment]
Hi - yes, please resolve the conflicts (you don't have to close the PR to do this).

**Comment by ben-stock** [comment]
Ok, we should be good to go then.

**Comment by ben-stock** [comment]
I have addressed the conflicts once again. If you want to have that list sorted by name, please let me know.

**Comment by emeryberger** [comment]
It seems a number of additions (Hacettepe University, among others) have been deleted. Please restore those.

**Comment by emeryberger** [comment]
Also yes, please sort by name (and don't check in the generated info or articles.json; I will update these automatically).

**Comment by ben-stock** [comment]
that was an effect of the new additions. I'll close this request, address the issues and open a new one.

**Pull request closed without merging**
