### PR TITLE
add Professors from Cornell and UW

### PR DESCRIPTION
**Pull request by cmavrogiannis**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Dieter Fox is Senior Director of Robotics Research at Nvidia; this is apparently a full-time, non-sabbatical position, so he does not meet the inclusion criteria.

**Comment by fycus-tree** [comment]
Sidd is already removed and in the industry.csv list. the others are Cornell ECE and MAE faculty and don't seem to satisfy inclusion criteria.

**Comment by cmavrogiannis** [comment]
All of the Cornell people are working on robotics and according to the inclusion criteria the home department does not matter. Also, both Sidd and Dieter are leading super active labs at UW, so I am not even sure why they have to be placed in the industry list.

**Comment by fycus-tree** [comment]
Can an ECE faculty be sole advisor for a CS PhD student? Can you point to that?

The [CS PhD Requirements](https://www.cs.cornell.edu/phd/current-students/phd-requirements) suggest the thesis committee chair must be a CS faculty. "The chair can be any member of the Field of Computer Science."

**Comment by cmavrogiannis** [comment]
Cornell follows the system of fields (every department, including CS): https://gradschool.cornell.edu/degrees-fields/

An ECE/MAE faculty that belongs to the CS field (quite common for robotics professors) may chair the committee of CS PhD students.

**Comment by fycus-tree** [comment]
Still not clear to me. For example, Rob, nowhere on [his cv](https://orl.mae.cornell.edu/shepherd-cv.pdf) mentions his CS Field affiliation. The word "computer" doesn't even show up.

**Comment by emeryberger** [comment]
Please clarify.

**Comment by emeryberger** [comment]
Closing for lack of response. Feel free to reopen.

**Pull request closed without merging**
