### PR TITLE
Remove INFOCOM from networks rankings, as it is not considered top-tier.

### PR DESCRIPTION
**Pull request by justinemarie**
Hi,
INFOCOM is not conisidered top-tier, and as it is a very large conference its inclusion skews rankings. This PR removes INFOCOM from the network/communications list.

### CODE REVIEW

**Comment by emeryberger** [comment]
I appreciate the PR but note this kind of change requires a process involving the relevant community (which will happen, but not this week).

**Comment by fycus-tree** [comment]
This might be a helpful resource
[Network Conference Statistics](https://www.cs.ucsb.edu/~almeroth/conf/stats/#infocom)
INFOCOM: 2017 -  20.9% rate, 294 papers accepted
SIGCOM: 2016 -  16.9%, 39 accepted
NSDI: 2012 - 17.8%, 30 accepted

For reference, a field like Vision has
CVPR: 2015 - 29.9%, 540 accepted
ECCV: 2014 - 26.8%, 363 accepted
ICCV:  2015 - 30.3%, 525 accepted

Theory:
FOCS: 2016 - 27.7%, 83 accepted
SODA: 2017 -  34.0%, 181 accepted
STOC 2017 - 24.4%, 103 accepted

[General Conference Rankings](http://www.guide2research.com/topconf/)
Edit: as a slight counter-point, manually going through a few top networking faculty from different institutions, they seem to greatly prefer to publish in NSDI or SIGCOM over INFOCOM [1](http://groups.csail.mit.edu/netmit/wordpress/publications/publications/) [2](http://nms.lcs.mit.edu/papers/index.php?authors_search=Balakrishnan&keyword_search=&function=search) [3](https://users.ece.cmu.edu/~vsekar/papers.html) [4](https://people.eecs.berkeley.edu/~istoica/pubs.html) [5](https://www2.eecs.berkeley.edu/Pubs/Faculty/shenker.html) [6](https://web.stanford.edu/~skatti/pubs.html) [7](https://www.cs.washington.edu/people/faculty/arvind/publications) [8](http://pages.cs.wisc.edu/~akella/wisr-webpage/publications.html)

**Comment by realstolz** [comment]
This might be another helpful data about skewed ranking

Computer networks 2015-2017
```
 R #T    S/N   I 	Institution
 1 49 = [  0  49 ]	Shanghai Jiao Tong University
 2 37 = [ 35   2 ]	University of California - Berkeley
 3 32 = [ 30   2 ]	Massachusetts Institute of Technology
 4 44 = [ 34  10 ]	Princeton University
 5 30 = [  1  29 ]	Tsinghua University
 6 22 = [ 11  11 ]	University of Michigan
 7 20 = [  5  15 ]	Technion - Israel Institute of Technology
 8 21 = [  3  18 ]	Ohio State University
 9 26 = [ 35   1 ]	Carnegie Mellon University
 9 23 = [ 13  10 ]	KAIST
11 19 = [ 10   9 ]	University of Illinois at Urbana-Champaign
11 16 = [  0  16 ]	University of Calgary
13 23 = [  7  16 ]	HKUST
14 21 = [  4  17 ]	Stony Brook University
15 19 = [  6  13 ]	University of Massachusetts Amherst
15 19 = [ 19   0 ]	Stanford University
17 22 = [  1  21 ]	USTC
18 22 = [ 20   2 ]	University of Washington
18 18 = [  1  17 ]	University at Buffalo
20 14 = [  0  14 ]	Nanyang Technological University
..
34 11 = [  9   2 ]	University of Wisconsin - Madison
..
37  9 = [  9   0 ]	Cornell University

  R: Rank based on S/N/I
S/N: SIGCOMM + NSDI
  I: INFOCOM

Type1: N/S >> I (e.g., UCB, MIT, Stanford)
Type2: N/S == I (e.g., UMich, KAIST, UIUC)
Type3: N/S << I (e.g., SJTU, THU, Calgary)
```
For brevity, the data directly uses the sum of #Pubs rather than the sum of Adj.#.

**Comment by ravenben** [comment]
While I don't have any additional data to offer (those above are excellent), I concur in that INFOCOM has been going downhill for over a decade, and is nowhere near SIGCOMM or NSDI in terms of prestige or average quality of work. There's also been issues with collusion and manipulation in the TPC process at INFOCOM in years past.

**Comment by emeryberger** [comment]
Per a survey of the community (NSDI & SIGCOMM PC members), which showed overwhelming support for NSDI & SIGCOMM and very low support for INFOCOM, INFOCOM has been removed.

**Comment by emeryberger** [comment]
networking-survey

**Pull request closed without merging**
