### PR TITLE
Update faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by DanHefetz**
Added Dan Hefetz as a CS faculty member

### CODE REVIEW

**Comment by emeryberger** [comment]
Please update your PR to include all faculty at Ariel. Thanks.

**Comment by emeryberger** [comment]
Thanks!

**Comment by DanHefetz** [comment]
Thank you!



Please note that for some reason one of our faculty members appears twice. This is Anat Paskin-Cherniavsky that also appears as Anat Paskin. Please delete the latter.



Best wishes,

Danny.





________________________________

**Comment by emeryberger** [comment]
That's on purpose. The system needs every version of an author's name under which they have authored papers. The file `dblp-aliases.csv` lists all aliases so the author only appears once in the rankings.

**Comment by DanHefetz** [comment]
And then the system will recognize her as one person?

Thanks,
Danny.

________________________________

**Comment by emeryberger** [comment]
Exactly.

**Pull request merged**
