### PR TITLE
Added IMDEA Networks Faculty

### PR DESCRIPTION
**Pull request by narseo**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
In doing a bit of follow-up on this PR, it appears that IMDEA doesn’t itself grant PhDs. If IMDEA researchers can solely advise PhD students at the relevant institution, they can be listed here, but if PhD students do not apply to IMDEA and instead are students at Carlos III (for example), then that institution should be listed. CSrankings is not intended to include institutions that do not grant PhDs.

**Comment by narseo** [comment]
It is true that IMDEA is not a  degree granting institution but this is also true for other indexed non-profit public research institutions such as MPI and IMDEA Software (one of the 7 institutes of the IMDEA initiative). Note, however, that our Ph.D students are supervised by a member of IMDEA Networks faculty and not by UC3M professors but they have double affiliation. Here is the list: 

https://www.networks.imdea.org/people/phd-students

Further, IMDEA Networks and its faculty team is responsible for interviewing, hiring, funding, and supervising the students independently from UC3M. Our Ph.D students carry out all their Ph.D work at IMDEA Networks.

**Comment by narseo** [comment]
Hi. Is any more information needed on your side?

**Comment by peey** [comment]
I want to clarify about this:
> but if PhD students do not apply to IMDEA and instead are students at Carlos III (for example), then that institution should be listed

Did you mean that the researchers should be listed as being affiliated to Carlos III, or did you mean that these researchers cannot be listed since they are affiliated to an institution (IMDEA) which itself does not grant degrees?

Regarding this and [this other remark](https://github.com/emeryberger/CSrankings/pull/674#issuecomment-354111194):

From the point of view of one of the use cases (prospective grad students looking at active researchers and institutes in their area), I would say that inclusion of these institutes / researchers is useful for discoverability. 

For instance, MPI is #1 in Europe in Programming Languages according to CSRankings. And students would want to find the faculty listed on these institutes since they advise PhD students irrespective of where the paperwork for the degree happens.

**Comment by narseo** [comment]
The students apply directly to IMDEA Networks Institute through our institutional website, so the researchers included in this pull request should be listed as IMDEA Networks faculty. A prospective student will go to our website, and not to UC3M's.

There are similar institutions already indexed such as MPI or IMDEA Software Institute (which is a separate institution, yet part of the IMDEA initiative)

**Comment by emeryberger** [comment]
Thanks for the discussion and information. I will accept the PR once the conflicts are resolved.

**Comment by narseo** [comment]
Thanks. I just resolved the conflicts.

**Pull request merged**
