### PR TITLE
modify faculty-affiliations.csv

### PR DESCRIPTION
**Pull request by mohiitgupta**

### CODE REVIEW

**Comment by emeryberger** [comment]
As I understand it, ECE faculty without courtesy appointments in CS cannot advise CS PhD students, and so are not eligible for inclusion in CSrankings. Can you confirm that these faculty have such appointments?

**Comment by mohiitgupta** [comment]
Hello,

All the mentioned faculties have courtesy appoinments in CS Department. I personally had a conversation about doing project with Prof. Sanjay Rao and I am an incoming CS graduate student. Kindly take a look here https://www.cs.purdue.edu/people/faculty/index.html

Thanks,
Mohit

**Comment by emeryberger** [comment]
I'd appreciate a single PR that comprehensively contains ECE faculty who can advise CS students.

**Comment by mohiitgupta** [comment]
Sure, will update the same PR.

**Comment by mohiitgupta** [comment]
Done.

**Comment by emeryberger** [comment]
Thanks.

**Pull request merged**
