### PR TITLE
Trying to fix my DBLP link, and also updating Prof. Gagan Agrawal's new affiliation.

### PR DESCRIPTION
**Pull request by catalyurek**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Augusta University is not in the database, so either it needs to be added in its entirety or the entry should be removed.

**Comment by catalyurek** [comment]
I am sorry I couldn't figure out how to properly map my name to your DBLP linking system

Even if we compete the "translateNameToDBLP" function with missing cedils and umlauts then the link would be 
https://dblp.uni-trier.de/pers/hd/=ccedil=/=Ccedil=ataly=uuml=rek:=Uuml=mit_V=

but that still doesn't work.  Without accents the link should be 

https://dblp.uni-trier.de/pers/hd/c/Catalyurek:Umit_V=

but that doesn't work either. 

proper DBLP person link is

https://dblp.uni-trier.de/pid/c/UmitVCatalyurek.html

May be only viable solution for such cases is to add this "pid" based DBLP info in your database. I tried to do that by putting Umit V Catalyurek as alias but that doesn't seem to work either.

I wish DBLP handled this a little bit more consistently.

**Comment by emeryberger** [comment]
@catalyurek I've sent a note to the DBLP folks; hopefully they will have a solution!

**Comment by emeryberger** [comment]
@catalyurek DBLP link should now be working for you (thanks to some help from the kind DBLP folks).

**Comment by catalyurek** [comment]
Thanks a lot!

**Pull request closed without merging**
