### PR TITLE
Added two new UHM faculty

### PR DESCRIPTION
**Pull request by scottrob3**
Peter Sadowski is a new full-time tenure track faculty member in the Computer Science Department.

Rick Kazman, a full-time tenured faculty member from another department at this University, has just been approved as a cooperating graduate faculty member in the Computer Science. This means that he can advise graduate students and serve as chair on graduate student committees in Computer Science.

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you point to a website that indicates this? This directory does not currently list Kazman: http://www.ics.hawaii.edu/people/

**Comment by scottrob3** [comment]
I haven’t added him yet. The Department  just voted on it on Friday. It’s possible that is isn’t official until I do some paperwork, I’m really not sure. If you like, we can leave it off until I can say that it is officially approved.
--------------------
Scott Robertson
scottrob3@gmail.com
http://www.ScottRobertson.info/

**Comment by scottrob3** [comment]
Hi Emery,
Actually, I will probably have another addition in about 3 weeks, so let’s put Rick Kazman and the new addition in the next batch. Then everything will be kosher. But, I would like to add Peter Sadowski at this time.

By the way, as a department Chair, I LOVE csrankings.org <http://csrankings.org/>. I feel that it is very fair and it gives me a set of criteria that I can ask my faculty to consider when they publish. I absolutely use it to discuss the Department’s research productivity with our administration, and I will use it as a measure of change over time.

-Scott
--------------------
Scott Robertson
scottrob3@gmail.com
http://www.ScottRobertson.info/

**Comment by emeryberger** [comment]
OK, I went ahead and manually added Sadowski.

**Pull request closed without merging**
