### PR TITLE
Rhul isg add

### PR DESCRIPTION
**Pull request by IddoTzameret**
… in last month's addition to Royal Holloway, University of London.
All can (and mostly are) supervising PhD students in CS.

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
You apparently edited the .csv with Excel. This does not work; it causes a lot of errors. (This is mentioned at the top of the contribution message, in italics.) Please try again.

**Comment by IddoTzameret** [comment]
Dear Emery, hi,

The file on github I merged in the second step *has not been edited at all by Excel* it is a clean text editting of your original file.

Addmitadly, I am a very beginning user of github. I did read your remarks in full, and took great notice not to use EXCEL, and of course I didn't use it. There was indeed an initial glitch in which EXCEL took over the file without me noticing it, after which I committed it. But this has now been fixed, as explained above.

I hope you may be able to merge it in any case. 

(Apologies, I do not have good command of github; hence it is hard for me to repeat these processes...).

Best,
Professor Iddo Tzameret 

On 27/04/2020 00:22:00, Emery Berger <notifications@github.com> wrote:
You apparently edited the .csv with Excel. This does not work; it causes a lot of errors. (This is mentioned at the top of the contribution message, in italics.) Please try again.

**Comment by emeryberger** [comment]
Yep, that's been fixed, thanks. I do see a few entries with "Royal Holloway, " (that is, with a comma in between); those will also need to be fixed.

**Comment by IddoTzameret** [comment]
Okay, apologies. I will do the whole process from scratch now, since I've
deleted the "flawed" repository.

---
Sent from my Android. Apologies for brevity, possible formatting anomalies
and autocorrect typos.

**Comment by IddoTzameret** [comment]
Done. From scratch. (No Excel use.)
Added faculty, and made sure to discard some commas in "Royal Holloway, University of London".
Pull request issued. 

Best,
--- Iddo
On 27/04/2020 11:17:41, Iddo Tzameret <iddo.tzameret@gmail.com> wrote:
Okay, apologies. I will do the whole process from scratch now, since I've deleted the "flawed" repository.


---
Sent from my Android. Apologies for brevity, possible formatting anomalies and autocorrect typos.

On Mon, 27 Apr 2020, 02:14 Emery Berger, <notifications@github.com [mailto:notifications@github.com]> wrote:

Yep, that's been fixed, thanks. I do see a few entries with "Royal Holloway, " (that is, with a comma in between); those will also need to be fixed.

**Pull request closed without merging**
