### PR TITLE
Add gamvrosi to csrankings.csv

### PR DESCRIPTION
**Pull request by gamvrosi**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by fycus-tree** [comment]
ECE department. Not on the CS PhD advisor list. Your own website recommends you apply to ECE not to CS.

**Comment by gamvrosi** [comment]
On CS PhD advisor list: https://www.csd.cs.cmu.edu/directory/faculty (external-facing website). 3 out of 4 PhDs currently CS students, and admitting from both depts every year.

**Comment by fycus-tree** [comment]
The [CS PhD guide](https://csd.cs.cmu.edu/sites/default/files/CSD-PhD-Handbook-2017-18.pdf) points to [http://www.cs.cmu.edu/~csd-grad/thesiscommittee.html](http://www.cs.cmu.edu/~csd-grad/thesiscommittee.html) which maintains the "Approved List". I was from someone who has access to this internal site that you're on the 40 person sized list of "Other Approved Faculty" (along with a dozen faculty from Business, a few from Philosophy, etc.) but not on the "Computer Science Department Faculty" tab. 

I just want to provide details for this topic. See #480 or #604

**Comment by gamvrosi** [comment]
There are 3 internal lists in CSD: the department (CSD) faculty, the college (SCS) faculty, and Other faculty. The ECE department falls under the College of Engineering (CIT), so all of its faculty will naturally fall under the "Other" category (since CIT != SCS). Everyone under "Other" can solely advise CS PhD students, and I thought that is enough to satisfy your qualification bar.

If you are suggesting that people under "Other" do not meet your criteria then professors such as Priya Narasimhan, Greg Ganger, Raj Rajkumar, Vyas Sekar, etc. who are currently in csrankings.csv should also be excluded.

**Comment by fycus-tree** [comment]
If you're suggesting that list is canonical and should be included, it'd be great if you made a pull request with all of these "Other" faculty, including the Philosophy (e.g. [Steve Awodey](https://www.andrew.cmu.edu/user/awodey/)) and Business (e.g. [Alan Scheller-Wolf](https://www.cmu.edu/tepper/faculty-and-research/faculty-by-area/profiles/scheller-wolf-alan.html)) faculty.

**Comment by gamvrosi** [comment]
Will do.

**Pull request merged**
