### PR TITLE
added University of Stuttgart

### PR DESCRIPTION
**Pull request by michaelpradel**

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you please pull again and resolve conflicts? Thanks!

**Comment by michaelpradel** [comment]
Done.

**Comment by emeryberger** [comment]
The diffs are too large for me to audit ("5,551 additions and 1,182 deletions"); please just have the commit include the added Stuttgart faculty.

**Comment by michaelpradel** [comment]
The pull request has only 26 added lines in csrankings.csv and 1 added line in country-info.csv. Where do you see "5,551 additions and 1,182 deletions"?

**Comment by emeryberger** [comment]
https://github.com/emeryberger/CSrankings/commit/920098135efbddaba70edb0767892a263b5f5535

**Comment by fycus-tree** [comment]
@emery the current commit isn't that (which is 9f8ab46 + 3d53411), but 9f8ab46 + 9200981 which I see as just 28 lines

**Comment by emeryberger** [comment]
nvm. merging.

**Comment by emeryberger** [comment]
Thanks!

**Pull request merged**
