### PR TITLE
Restore pie chart code and allow users to select it

### PR DESCRIPTION
**Pull request by minsukkahng**
Hi Emery,

This is response to your request on allowing users to select pie charts (at #4067). I've added a dropdown to the instruction. When a user switches to another chart type, "/chart/pie" is added to the URL and "this.rank" is called. Although the page may not need to be refreshed, if we don't, I think we will make the problem too complicated (e.g., what if they change the chart type when a few charts are already being displayed).

Thanks again.

Cheers,
Minsuk

### CODE REVIEW

**Comment by emeryberger** [comment]
Awesome! Can you go ahead and remove the generated files (`csrankings.min.js`, `csrankings.js`) from the commit? (There are currently conflicts with the former.)

**Comment by minsukkahng** [comment]
The js files are now updated.

**Comment by emeryberger** [comment]
I may be missing something but I didn't see any updates to the `navigation` function for parsing the URL?

**Comment by minsukkahng** [comment]
Oh another function to be updated. Just pushed another commit.

**Comment by emeryberger** [comment]
Merged, thanks! One minor note: the switch from bar to pie doesn't change the icon choice.

**Comment by minsukkahng** [comment]
Thank you! I had tried it (switching the icon from bar to pie), but my first try didn't work (likely because the html rows are not re-rendered), and it seemed to require some refactoring. I hope some open-source contributor can do it for us.

**Comment by emeryberger** [comment]
Fixed with the above.

**Pull request merged**
