### PR TITLE
Updated faculty list and homepage URLs for IST Austria

### PR DESCRIPTION
**Pull request by clampert**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Please read and indicate you agree with **all** these guidelines to getting your pull request accepted. Note that pull requests may take some time to get merged (please don't contact us for at least three months for updates, unless you are a sponsor - see below).

**If you find CSrankings useful, [please consider becoming a sponsor](https://github.com/sponsors/csrankings).**

**NOTE:** IF YOU DO NOT FOLLOW THE STEPS BELOW, YOUR PULL REQUEST WILL BE SUMMARILY REJECTED.
You must read and check **all** the boxes below by filling them in with an X or your PR will be rejected.

**The Basics**

- [X] All pull requests and issues must come from non-anonymous accounts. Make sure your GitHub profile contains your full name.

- [X] Use a reasonable title that explains what the PR corresponds to (as in, not "Update csrankings-x.csv").

- [X] Combine multiple updates to a single institution into a **single PR.**

- [X] Only submit one pull request per institution.

- [X] Do not modify any files except `csrankings-[a-z].csv` or (if needed) `country-info.csv` and `old/industry.csv` (see below).

- [X] Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use the GitHub user interface or a text editor like emacs or NotePad instead.

- [X] Insert new faculty **in alphabetical order** (not at the end) in the appropriate `csrankings-[a-z].csv` files. **Do not modify `csrankings.csv`, which is auto-generated.**

- [X] Check to make sure that you have no spaces after commas, or any missing fields.

- [X] Check to make sure the home page is correct.

- [X] Make sure the Google Scholar IDs are just the alphanumeric identifier (not a URL or with `&hl=en`).

- [X] Check to make sure the name corresponds to the DBLP entry (look it up at http://dblp.org).

- [X] If a faculty member is not in a CS department or similar, include a comment explaining how they meet the inclusion criteria (see below).

**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track research
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. **Provide justification, pointing to specific home pages
showing how faculty not in a CS department meet the inclusion criteria,
e.g. showing a courtesy appointment in CS.** Faculty must also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings-[a-z].csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put `NOSCHOLARPAGE`.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire CS faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings-[a-z].csv` (**the letters correspond to the first letter of the faculty members' names**); include disambiguation suffixes like `0001` as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, *all of them need to be listed*. Do not update `dblp-aliases.csv`.

- [X] If the institution you are adding is not in the US,
update `country-info.csv` and add *all* of the faculty in the CS department.

**(Advanced) Quick contribution via a shallow clone** 

We recommend that you use the GitHub web user interface to make changes. However, it may be more convenient
to clone the repository for larger-scale changes.

However, a full clone of the CSrankings repository is almost 2GB.  To
contribute a change without creating a full local clone of the
CSrankings repo, you can perform a _shallow clone_.  To do so, follow these
steps:

1. Fork the CSrankings repo.  If you have an existing fork, but it is not up to date with the main repository, this technique may not work.  If necessary, delete and re-create your fork to get it up to date.  (Do **not** delete your existing fork if it has unmerged changes you want to preserve!)

1. Do a shallow clone of your fork: `git clone --depth 1 https://github.com/yourusername/CSrankings`.  This will only download the most recent commit, not the full git history.

1. Make your changes on a branch, push them to your clone, and create a pull request on GitHub as usual.

If you want to make another contribution and some time has passed, perform these steps again, creating a fresh fork and shallow clone.

### CODE REVIEW

**Comment by emeryberger** [comment]
Tons of errors here from DBLP; many faculty are not present there, which is a pretty clear signal that the names are wrong or that the faculty are not computer scientists. Closing.

This is from the validation check:

```
Run python validate_commit.py $DIFF
Sanity checking the commit. Please check any issues raised here.
Processing Anna Kicheva,IST Austria,https://ista.ac.at/research/research-groups/kicheva-group,zBpAlHkAAAAJ
  ERROR: Invalid name (Anna Kicheva). Please ensure it matches the DBLP entry.
  Checking homepage URL (https://ista.ac.at/research/research-groups/kicheva-group)
***Test failure for Anna Kicheva***.
Processing Beatriz Vicoso,IST Austria,https://ista.ac.at/research/research-groups/vicoso-group,4Wqy1IcAAAAJ
  ERROR: Invalid name (Beatriz Vicoso). Please ensure it matches the DBLP entry.
  Checking homepage URL (https://ista.ac.at/research/research-groups/vicoso-group)
***Test failure for Beatriz Vicoso***.
Processing Bernd Bickel,IST Austria,https://ista.ac.at/research/research-groups/bickel-group,Bt-QKXYAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3ABernd%20Bickel:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/bickel-group)
Processing Björn Hof,IST Austria,https://ista.ac.at/research/research-groups/hof-group,tytU38QAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3ABj%C3%B[6](https://github.com/emeryberger/CSrankings/actions/runs/6344022156/job/17233196528?pr=6372#step:6:7)rn%20Hof:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/hof-group)
Processing Calin C. Guet,IST Austria,https://ista.ac.at/research/research-groups/guet-group,J4NGQxcAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3ACalin%20C%20Guet:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/guet-group)
Processing Carl-Philipp Heisenberg,IST Austria,https://ista.ac.at/research/research-groups/heisenberg-group,NOSCHOLARPAGE
  Checking https://dblp.org/search/author/api?q=author%3ACarl%20Philipp%20Heisenberg:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/heisenberg-group)
Processing Chris Wojtan,IST Austria,https://pub.ista.ac.at/~wojtan/,OGdXlpcAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AChris%20Wojtan:$%3A&format=json&c=10
  Checking homepage URL (https://pub.ista.ac.at/~wojtan/)
Processing Christoph H. Lampert,IST Austria,http://cvml.ista.ac.at,iCf3SwgAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AChristoph%20H%20Lampert:$%3A&format=json&c=10
  Checking homepage URL (http://cvml.ista.ac.at)
Processing Christoph Lampert,IST Austria,http://cvml.ista.ac.at,iCf3SwgAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AChristoph%20Lampert:$%3A&format=json&c=10
  Checking homepage URL (http://cvml.ista.ac.at)
Processing Christopher Wojtan,IST Austria,https://pub.ista.ac.at/~wojtan/,OGdXlpcAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AChristopher%20Wojtan:$%3A&format=json&c=10
  Checking homepage URL (https://pub.ista.ac.at/~wojtan/)
Processing Dan Alistarh,IST Austria,https://ista.ac.at/research/research-groups/alistarh-group,[7](https://github.com/emeryberger/CSrankings/actions/runs/6344022156/job/17233196528?pr=6372#step:6:8)5q-6ZQAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3ADan%20Alistarh:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/alistarh-group)
Processing Eleftherios Kokoris-Kogias,IST Austria,https://ista.ac.at/en/research/kokoris-group,7TOIlqkAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AEleftherios%20Kokoris%20Kogias:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/en/research/kokoris-group)
Processing Eva Benkova,IST Austria,https://ista.ac.at/research/research-groups/benkova-group,NOSCHOLARPAGE
  ERROR: Invalid name (Eva Benkova). Please ensure it matches the DBLP entry.
  Checking homepage URL (https://ista.ac.at/research/research-groups/benkova-group)
***Test failure for Eva Benkova***.
Processing Francesco Locatello,IST Austria,https://www.francescolocatello.com,wQanfTIAAAAJ
  Checking homepage URL (https://ista.ac.at/research/research-groups/siegert-group)
***Test failure for Sandra Siegert***.
Processing Simon Hippenmeyer,IST Austria,https://ista.ac.at/research/research-groups/hippenmeyer-group,DQKripgAAAAJ
  ERROR: Invalid name (Simon Hippenmeyer). Please ensure it matches the DBLP entry.
  Checking homepage URL (https://ista.ac.at/research/research-groups/hippenmeyer-group)
***Test failure for Simon Hippenmeyer***.
Processing Sylvia Cremer,IST Austria,http://ista.ac.at/research/research-groups/cremer-group,_Gm-T[9](https://github.com/emeryberger/CSrankings/actions/runs/6344022156/job/17233196528?pr=6372#step:6:10)IAAAAJ
  ERROR: Invalid name (Sylvia Cremer). Please ensure it matches the DBLP entry.
  Checking homepage URL (http://ista.ac.at/research/research-groups/cremer-group)
***Test failure for Sylvia Cremer***.
Processing Tamas Hausel,IST Austria,https://ista.ac.at/research/research-groups/hausel-group,o2Bj63wAAAAJ
  ERROR: Invalid name (Tamas Hausel). Please ensure it matches the DBLP entry.
  Checking homepage URL (https://ista.ac.at/research/research-groups/hausel-group)
***Test failure for Tamas Hausel***.
Processing Thomas A. Henzinger,IST Austria,http://pub.ista.ac.at/~tah,jpgplxUAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AThomas%20A%20Henzinger:$%3A&format=json&c=[10](https://github.com/emeryberger/CSrankings/actions/runs/6344022156/job/17233196528?pr=6372#step:6:11)
  Checking homepage URL (http://pub.ista.ac.at/~tah)
Processing Uli Wagner,IST Austria,https://ista.ac.at/research/research-groups/wagner-group,9sN4N1wAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AUli%20Wagner:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/wagner-group)
Processing Uli Wagner 0001,IST Austria,https://ista.ac.at/research/research-groups/wagner-group,9sN4N1wAAAAJ
  Checking https://dblp.org/search/author/api?q=author%3AUli%[20](https://github.com/emeryberger/CSrankings/actions/runs/6344022156/job/17233196528?pr=6372#step:6:21)Wagner%200001:$%3A&format=json&c=10
  Checking homepage URL (https://ista.ac.at/research/research-groups/wagner-group)
ERROR: This PR has too many diffs. Something probably went wrong.


```

**Comment by clampert** [comment]
> Tons of errors here from DBLP; many faculty are not present there, which is a pretty clear signal that the names are wrong or that the faculty are not computer scientists. Closing.

Agreed, but these are in the file from a much earlier import. I only updated their affiliation and homepages, as the web links have changed.

**Comment by emeryberger** [comment]
That's fine, but please remove them so the validity checks pass. Thanks.

**Comment by clampert** [comment]
> That's fine, but please remove them so the validity checks pass. Thanks.

OK.

**Pull request closed without merging**
