### PR TITLE
Add University of York academics from Real-time Group

### PR DESCRIPTION
**Pull request by habilain**
Hi,

This is a commit which adds the academics from the University of York real-time group. I'm not entirely certain why the diff for homepages is so large; probably a difference of opinion in sorting order between the original program and LibreOffice.

If there's anything I can do to help, just let me know.

- David Griffin

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi - please re-pull and edit the homepages.csv so the commit is smaller. More importantly, I don't take individuals or groups as the initial commit for a department; please update with all full-time, tenure-track CS faculty. Thanks.

**Comment by habilain** [comment]
I fear that adding the entire department may be something that I am unable to do for lack of authority to do it - I was only asked to add the RTS group, and I certainly can't make decisions for the department as a whole. I'll close this pull request for now and raise it with the appropriate people, and see where that leads.

**Comment by emeryberger** [comment]
That is fine, but faculty affiliations, etc., are generally public information.

**Comment by habilain** [comment]
True, but you yourself do not do updates. I myself am not a permanent member of staff, so I cannot commit to keeping the information up-to-date, and I don't think any of the permanent members of the RTS group are willing/able to do so. I suspect this means that there needs to be a decision taken by the department (as opposed to the RTS group) which will either be that the department will submit the information to CSRankings and keep it up to date, or will not submit any information. I doubt that the middle third option, submitting the required data now and then not keeping it up-to-date because no-one outside of the RTS group is aware of it would be good for anyone.

In any case, the decision on how to engage with CSRankings shouldn't be made by me, so I'll wait until someone with the correct authority makes the decision.

**Comment by emeryberger** [comment]
That's fine. (FWIW I routinely enter updates submitted either via github or the online form. And by routinely, I mean _often_.)

**Pull request closed without merging**
