### PR TITLE
Renamed category, added ICLR, moved KDD to next tier.

### PR DESCRIPTION
**Pull request by emeryberger**
"Machine Learning & Data Mining" is now "Machine Learning". ICLR has been incorporated, per frequent request. To abide by the top-3 limit, KDD has been moved to a next tier (off by default, still included as a checkbox).

### CODE REVIEW

**Comment by emeryberger** [comment]
Closes https://github.com/emeryberger/CSrankings/pull/4529, https://github.com/emeryberger/CSrankings/issues/4970, https://github.com/emeryberger/CSrankings/issues/4683, https://github.com/emeryberger/CSrankings/issues/4442, https://github.com/emeryberger/CSrankings/issues/3518.

**Comment by yhn112** [comment]
Some kind of a bug:
After checking the box next to Machine Learning to enable the entire category, ICLR is still off

Screenshot 2022-12-04 at 00 22 30

**Comment by emeryberger** [comment]
Yep, found it before I saw this and fixed it :). Thanks for reporting!

**Comment by xiaohk** [comment]
How about moving KDD to `AI` or `The Web & information retrieval`? Both categories only have two conferences each.

**Comment by ChandlerBang** [comment]
I would also agree with moving KDD to `AI` or `The Web & information retrieval`. For example, the topics studied in KDD has substantial overlap with that in WWW.  KDD is always considered as the top conference in data mining and it deserves a top tier in csrankings.org.  

It would also be of interest to create another subarea named `Data Mining` under Artificial Intelligence, and have both KDD and WWW in it.

**Comment by ninghaohello** [comment]
I also strongly agree with moving KDD to `The Web & information retrieval` instead of simply putting it to the next tier. KDD is the top conference in data mining, and is in the same tier as SIGIR and WWW.

Also, the name `The Web & information retrieval` can be changed into "Web information retrieval & Data Mining" or simply "Information Retrieval & Data Mining" (widely used in our domain).

**Comment by xiabenhu** [comment]
I would suggest to add one more data mining category under AI rather than simply removing KDD.

There are only 5 areas under AI, which is significantly inconsistent with the impact of AI as well as the # of participants in AI.

**Comment by yzhao062** [comment]
First of all, I totally agree to add ICLR to the list. Meanwhile, I would argue that simply removing an important conference like KDD from the list is too bold. As data mining researchers, we have already faced the issue that only KDD is taken into account in csranking, while WSDM and ICDM are not. I would recommend adding a new category under AI called data mining, and including KDD, WSDM, and ICDM. This seems a better fix than removing KDD from ML...

**Comment by Romanticone** [comment]
KDD is the best conference in Data Mining. It is unreasonable to exclude it from the top conferences.

**Comment by BuleSky233** [comment]
I would also agree with moving KDD to AI or The Web & information retrieval.

**Comment by Rachelxuan11** [comment]
Thanks for this post. I agree to include ICLR too. And I am sorry to see that KDD is removed from top conferences of Machine Learning & Data Mining, which would undermine contributions from the data mining community. If it must be excluded from the current Machine Learning top conferences. At least, I suggest to open a new track for data mining. Or please put it in the Web & Information retrieve track.

**Pull request merged**
