### PR TITLE
Faculty members with IIIS, Tsinghua University

### PR DESCRIPTION
**Pull request by chenming-wu**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by chenming-wu** [comment]
Institute for Interdisciplinary Information Sciences (IIIS) established on December 30, 2010, held the inauguration ceremony on January 15, 2011. Prof. Andrew Chi-Chih Yao, Dean of the Institute, is a world-leading computer scientist, winner of the A.M. Turing Award in 2000, member of the Chinese Academy of Sciences,  foreign member of the US National Academy of Sciences and the American Academy of Arts and Sciences. The Institute aims to become one of the leading research centers on interdisciplinary information sciences in the world as well as to offer a habitat for the research and education of computer science and quantum information science in China.

-Ref: http://iiis.tsinghua.edu.cn/en/about/

All PhD students working on computer science problems in IIIS will obtain a Computer Science degree from Tsinghua university.

**Review by emeryberger — DISMISSED** [review]
Your updates have messed with the encodings of several institutions. Please fix.

**Comment by emeryberger** [comment]
The reference provided does not indicate that these faculty can singly advise PhD students in CS. Please clarify / find other support. Thanks.

**Comment by chenming-wu** [comment]
Thanks for your feedback!

"The IIIS Graduate Program aims to nurture top-class creative students and to achieve academic excellence competitive with the top ten computer science departments in the world. "
Ref1: http://iiis.tsinghua.edu.cn/en/list-538-1.html

The enrollment notice page shows that 
"清华大学交叉信息研究院现招收计算机科学与技术专业2015级直博生和硕士研究生。"
which can be translated by Google as "Tsinghua University Institute of Interdisciplinary Information Technology is now enrolled in computer science and technology 2015 Straight Bosheng and master's degree ."
However, "Straight Bosheng" is not a correct translation. In Chinese, it means "five-years PhD program without Master's degree", which is slightly different from "Normal Bosheng" that requires candidates have a Master's degree.

Ref2: http://iiis.tsinghua.edu.cn/en/show-3913-1.html
Translated page of Ref2: https://translate.google.com.hk/translate?hl=zh-CN&ie=UTF8&prev=_t&sl=zh-CN&tl=en&u=http://iiis.tsinghua.edu.cn/en/show-3913-1.html

**Comment by chenming-wu** [comment]
Hi Professor, do you need any other support to indicate they can advise PhD students?

**Comment by chenming-wu** [comment]
Hi Professor. It seems like this pull request is still under review. Is there any problem inside this PR? Maybe I can revise it later on. :-)

**Pull request merged**
