### PR TITLE
New faculty to RIT

### PR DESCRIPTION
**Pull request by andymeneely**

### CODE REVIEW

**Comment by emeryberger** [comment]
Can you please confirm that all these faculty are full-time, tenure track faculty who can advise PhD students in the CS department or similar? It's not obvious because at least one of them is in the SE department. Thanks.

**Comment by andymeneely** [comment]
If you're thinking of Dan Krutz, he is tenure-track now. We just hired him to our tenure line, and he was a lecturer. Our website hasn't been updated, but trust me, he's signed the papers :)

**Comment by emeryberger** [comment]
In addition, Pradeep Murukannaiah is listed as Instructional Faculty here: 
http://www.rit.edu/gccis/people

AFAICT faculty in the SE department are not automatically part of the CS college.

**Comment by andymeneely** [comment]
Pradeep is an assistant professor in our department - starting this semester, actually.

The SE department is part of the College of Computing and Information Science.

**Comment by emeryberger** [comment]
OK, thanks for the clarification.

**Pull request merged**
