### PR TITLE
Added Kijung Shin (KAIST)

### PR DESCRIPTION
**Pull request by kijungs**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.
Please see [link](https://ee.kaist.ac.kr/professor_s2?language=en&filter_prefix=0&field_profile_position_tid=_none&field_profile_building_tid=_none&combine=Kijung) for eligibility.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by kijungs** [comment]
Please see [link](https://ee.kaist.ac.kr/professor_s2?language=en&filter_prefix=0&field_profile_position_tid=_none&field_profile_building_tid=_none&combine=Kijung) for eligibility. If it is not enough, please let me know how I can prove that I am eligible.

**Comment by emeryberger** [comment]
Not listed here: https://cs.kaist.ac.kr/people/faculty?kind=&gubun=S&gubun_lang=en&research_area=&keyword=&radio_lang=en

I need evidence that you can solely advise a PhD student _in CS_. This generally requires an affiliate appointment.

**Comment by kijungs** [comment]
Thanks for the clarification! 

While I do not belong to the School of Computing, I belong to the computer group in the School of EE.
At KAIST, both the School of EE and the School of Computing have computer groups.
The curriculum and **18 full-time faculty members** of the computer group of the School of EE can be found [here](https://ee.kaist.ac.kr/under_curr?combine=&field_curriculum_category_tid_i18n%5B%5D=23) and [here](https://ee.kaist.ac.kr/professor_s2?language=en&field_profile_position_tid=_none&field_profile_category_tid%5B%5D=23&field_profile_building_tid=_none&combine=).
All the faculty members publish papers in the CS conferences considered in http://csrankings.org/, and many of the faculty members are on the list.
Computer science Ph.D. students at KAIST can choose one between the two groups, and I can solely advise students in the computer group of the School of EE.

Thanks for your help!!

**Comment by emeryberger** [comment]
This seems to fail the inclusion eligibility requirement. Please read the requirement in line 1 carefully. You need to be able to solely advise someone _in CS_ for a _CS_ PhD.

**Pull request closed without merging**
