### PR TITLE
Update University of Surrey(UK) Computer Vision group

### PR DESCRIPTION
**Pull request by AyanKumarBhunia**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
You checked this entry, but it appears this PR does not include the entire faculty. A subset of the faculty is not sufficient; please add them all.

> If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

**Comment by AyanKumarBhunia** [comment]
https://www.surrey.ac.uk/centre-vision-speech-signal-processing

Hi, I have updated all the professor's details from CVSSP, University of Surrey. 

Rest of the faculty from Electrical Engineering department are not related to Computer Science. It is a specific research groups on Vision, Speech, and Signal Processing.

**Comment by emeryberger** [comment]
Please read the inclusion requirements more carefully.

> Eligible faculty include only full-time, tenure-track faculty members on a given campus who can advise PhD students in Computer Science. Faculty not in a CS department or similar who can advise PhD students in CS can be included regardless of their home department.

The crucial part is *in CS*. The fact that ECE professors are doing CS work is immaterial; the question is whether they meet the above criteria.

**Comment by AyanKumarBhunia** [comment]
Adrian Hilton,University of Surrey,https://www.surrey.ac.uk/people/adrian-hilton,vTIYTNQAAAAJ
Jean-Yves Guillemaut,University of Surrey,http://personal.ee.surrey.ac.uk/Personal/J.Guillemaut/,xd8Ej6YAAAAJ
Simon Hadfield,University of Surrey,http://personal.ee.surrey.ac.uk/Personal/S.Hadfield/biography.html,KuQs_N0AAAAJ
Richard Bowden,University of Surrey,http://personal.ee.surrey.ac.uk/Personal/R.Bowden/,mvvgDvcAAAAJ
Josef Kittler,University of Surrey,https://www.surrey.ac.uk/people/josef-kittler,pk-yb_kAAAAJ
Christopher Russell,University of Surrey,https://www.surrey.ac.uk/cvssp/people/russell_christopher/,RM2sHhYAAAAJ 
Miroslaw Bober,University of Surrey,https://www.surrey.ac.uk/people/miroslaw-bober,rmATQ28AAAAJ
John Collomosse,University of Surrey,http://personal.ee.surrey.ac.uk/Personal/J.Collomosse/,yVnCUg0AAAAJ
Helen Treharne,University of Surrey,https://www.surrey.ac.uk/people/helen-treharne,Fx_tCYMAAAAJ
Ioana Boureanu,University of Surrey,http://people.itcarlson.com/ioana/,yQu36nIAAAAJ
Liqun Chen,University of Surrey,https://www.surrey.ac.uk/people/liqun-chen,3IH9iokAAAAJ
Brijesh Dongol,University of Surrey,https://brijeshdongol.github.io/,fjA_2-cAAAAJ
François Dupressoir,University of Surrey,https://fdupress.net/,gxFJ_bYAAAAJ
Lee Gillam,University of Surrey,https://www.surrey.ac.uk/people/lee-gillam,8GJC9fAAAAAJ
Yaochu Jin,University of Surrey,http://www.soft-computing.de/jin.html,B5WAkz4AAAAJ
Manal Helal,University of Surrey,https://www.surrey.ac.uk/people/manal-helal,fgACIMUAAAAJ
Paul Krause,University of Surrey,https://www.surrey.ac.uk/people/paul-krause,6d3d0vwAAAAJ
Yunpeng Li,University of Surrey,https://www.surrey.ac.uk/people/yunpeng-li,JzyKdRUAAAAJ
Kaitai Liang,University of Surrey,https://www.surrey.ac.uk/people/kaitai-liang,_qHKRH4AAAAJ
Mark Manulis,University of Surrey,http://manulis.eu/,MdmQAVkAAAAJ
Sotiris Moschoyiannis,University of Surrey,https://www.surrey.ac.uk/people/sotiris-moschoyiannis,lXpUuUoAAAAJ  
Manos Panaousis,University of Surrey,https://www.manospanaousis.com/FRwRt24AAAAJ
Steve Schneider,University of Surrey,https://www.surrey.ac.uk/people/steve-schneider,RpVDhIoAAAAJ
Alireza Tamaddoni Nezhad,University of Surrey,https://www.surrey.ac.uk/people/alireza-tamaddoni-nezhad,a8_fGh4AAAAJ

**Comment by emeryberger** [comment]
Manually added.

**Pull request closed without merging**
