### PR TITLE
Corrections and Updates to UMD faculty and 1 CMU faculty

### PR DESCRIPTION
**Pull request by saptab**
I have corrected faculty details in UMD. I also added faculty details in UMD. However, there is a strange issue that the records of Prof. Mihai Pop, Prof. Alan Sussman and Prof. Howard C. Elman are present but are not showing up in the ranking. Removed Prof. Jaime Carbonell in CMU after his death in February. 

Another strange thing is only 20 records are modified. But it is showing (+20491 additions) and (-20471 deletions) which does give the 20 number when considered together. I am not sure why it was treated like this. I have the source csv file with me which I can share with you, if you need it.

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please try again (and move departed faculty to `old/rip.csv`). Presumably line endings have changed -- I can't take a diff that's this big, for obvious reasons.

**Comment by saptab** [comment]
Thank you very much. I shall do so.

KIndly guide as to why the records of Prof. Mihai Pop, Prof. Alan Sussman and Prof. Howard C. Elman are present in the csv file but are not showing up in the ranking.

**Comment by emeryberger** [comment]
Check the articles.json file to verify they are being indexed.

**Comment by emeryberger** [comment]
It is certainly possible that their DBLP names are not correct or that they have not published papers in CSrankings conferences in the last decade.

**Comment by saptab** [comment]
I shall check the articles.json file as advised.

The DBLP names were correct and all 3 professors published in the last decade.

**Pull request closed without merging**
