### PR TITLE
Add faculty members from Czech Technical University in Prague, Faculty of Electrical Engineering

### PR DESCRIPTION
**Pull request by asch**
**Inclusion criteria**

- [X] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department. Faculty should also have a 75%+ time appointment (check
`old/industry.csv` for faculty who are now more than 25% in industry).

**Updating an affiliation or home page**

- [X] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [X] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [X] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [X] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [X] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
It's not obvious that all of these faculty are eligible for inclusion, since some aren't in a Department of Computer Science (e.g., Cybernetics or EE). Please remove any who cannot solely advise a PhD student _in Computer Science_.

**Comment by asch** [comment]
All listed faculties are eligible to solely advise PhD students in Computer Science Program. All listed faculties are from CS Department or Dpt. of Cybernetics which are part of the Faculty of Electrical Engineering and these departments guarantee CS study programme on that faculty. Dpt. of Cybernetics is more focused on Robotics and Vision however CS Department is more on Machine Learning, Game Theory, Planning and SW Engineering. The reason for two departments is organizational and historical and both departments are actually CS departments in the world context. By the way, there are already 3 other professors from the Dpt. of Cybernetics in the database.

**Comment by emeryberger** [comment]
Sounds good, thanks for the clarification.

**Comment by emeryberger** [comment]
One note: the name of your institution is quite long for the UI (in fact, the longest in Europe), and I will be abbreviating these. I propose that it be shortened to "Czech Technical University" as there is currently no ambiguity, but if you have another suggestion, please let me know.

**Comment by asch** [comment]
Yes, Czech Technical University is the common abbreviation of the formal institution name.

**Pull request merged**
