### PR TITLE
Add Adam M. Smith from UC Santa Cruz

### PR DESCRIPTION
**Pull request by rndmcnlly**
I'm in the department of Computational Media, but, yes, I can be the sole advisor of CS PhD students.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please point to a web page indicating this; your name does not appear here (while others do appear as adjuncts): https://www.soe.ucsc.edu/departments/computer-science/people/faculty#S

**Comment by rndmcnlly** [comment]
I'm listed here: https://www.soe.ucsc.edu/departments/computational-media/people/faculty#S

**Comment by emeryberger** [comment]
Right, but that page (in the Department of Computational Media) doesn't indicate that you can solely advise PhD students in the CS Department.

**Comment by rndmcnlly** [comment]
I don't know what I can point to publicly that indicates this. I currently have a sole-advised CS PhD student, and the Memorandum of Understanding between our departments states the following:

> This MOU establishes a reciprocal agreement between Computer Science and Computational Media in which faculty can be the instructor of record for senior theses, independent studies, and advisors or joint advisors on PhD or Master’s level theses and projects.

In a few years I could point to a dissertation cover page as evidence, but I'm just getting started.

**Comment by emeryberger** [comment]
That MoU sounds like more than enough - is this not public? For now, I will treat this discussion as documentation, but if you can find a public link or post that publicly and comment here, that'd be much appreciated.

**Pull request merged**
