### PR TITLE
Adding SE at UT

### PR DESCRIPTION
**Pull request by gliga**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

_Do not use Excel to edit any .csv files; Excel incorrectly tries to
convert some Google Scholar entries to formulas, corrupting the
database. Use a text editor like emacs or NotePad instead._

**Inclusion criteria**

- [ ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [ ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [ ] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Not listed here as adjunct or affiliated: https://www.cs.utexas.edu/people

**Comment by gliga** [comment]
Thanks for taking a look at the request.

On http://csrankings.org/ it says "Please verify that the faculty members are full-time, tenure-track faculty who can solely advise a PhD student in Computer Science, and that their names are as they appear in DBLP". The specified requirements are satisfied. Thanks.

**Comment by emeryberger** [comment]
The inclusion criteria are for a PhD in _Computer Science_. In the case of UT-Austin, there is a CS department which grants PhDs in "computer science", not computer engineering (say). Included faculty need to be able to solely advise PhD students in that department.

**Comment by gliga** [comment]
Dear Emery,

Thanks for the prompt response.

Boundaries at UT across departments for graduate students are rather
flexible.  If there is a student and a faculty member that share
common interests, it naturally happens that the faculty (as a gsc
member) is a sole supervisor of the student.  Although I have not
tested this for every department, I believe it holds across the
campus.  For example,
https://catalog.lib.utexas.edu/record=b9792366~S29 (bottom of the
page).  Library is likely the only place that has all the examples.

**Comment by emeryberger** [comment]
Interesting. It would be helpful if you could point to a webpage with specific policy information.

**Comment by emeryberger** [comment]
Closing for lack of response. Feel free to reopen with info on web page as requested.

**Pull request closed without merging**
