### PR TITLE
Added Noboru Matsuda at North Carolina State University

### PR DESCRIPTION
**Pull request by nmazda**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x ] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x ] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [ ] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
If you look at the diffs, you will see a lot of broken entries. Please only include the diff for your entry.

**Comment by nmazda** [comment]
Hi,

Thanks for the kind and prompt follow up.   I really appreciate your assistance.   

I very carefully followed the instruction on the http://csrankings.org <http://csrankings.org/> for "pull request”, in particular by following the URL below:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github <https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github>

I honestly have little idea what you mean by “only include the diff”.  I’m sorry!!!

All what I did was to add a following single line to csrankings.csv:

Noboru Matsuda	North Carolina State University	https://people.engr.ncsu.edu/nmatsud/	T7eGKqAAAAAJ

Would you please help me how to make things straight from here?

Best regards,
Noboru

--
Noboru Matsuda  (http://go.ncsu.edu/Matsuda)

  Director, Innovative Educational Computing Lab
  Associate Professor
  Department of Computer Science
  North Carolina State University

**Comment by emeryberger** [comment]
If you look here, you will see that there are a number of lines that have been spuriously modified.

https://github.com/emeryberger/CSrankings/pull/1165/commits/cad7a722d9df9ee1da75c31beedaf586b89e4be1

In any event, I will close and add you manually.

**Comment by nmazda** [comment]
Oh, I see.   I’m so sorry for the slip.  I’ll try it again.   I really appreciate your kind follow up.  Very helpful.   Thank you so much for maintaining the CS Ranking site!!

Best,
Noboru

**Pull request closed without merging**
