### PR TITLE
missing cmu faculty

### PR DESCRIPTION
**Pull request by leonidk**
# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [x] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [x] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

# Notes
All of these professors do advise PhD students in the School of Computer Science. A link to current and former PhD students advised by each professor can be found on the "Students/Affiliates"  tab of the website. If you click on the PhD student, you can find their thesis document.

### CODE REVIEW

**Comment by emeryberger** [comment]
Please remove non-tenure track faculty, who are not currently eligible for inclusion (tenure-track only at this time), e.g., https://www.ri.cmu.edu/ri-faculty/katia-sycara/. Thanks.

**Comment by fycus-tree** [comment]
I think that policy is somewhat problematic. Many of the professors that teach courses, advise students, etc. at CMU are research professors. This is not a short-term adjunct position. For example, Professor Sycara (your example) has been here for over 30 years and has a wealth of personal accomplishments ([wiki](https://en.wikipedia.org/wiki/Katia_Sycara),[dblp](https://dblp.uni-trier.de/pers/hd/s/Sycara:Katia_P=),[scholar](https://scholar.google.com/citations?user=VWv6a9kAAAAJ&hl=en)) . Research professors have a slightly different position that doesn't require they teach courses, although many do. 

I'll update the pull request but wanted to voice my critique.

**Comment by leonidk** [comment]
done

**Comment by emeryberger** [comment]
Thanks - please resolve conflicts and I will merge.

**Comment by leonidk** [comment]
done

**Pull request merged**
