### PR TITLE
Add Jeff Clune from the University of Wyoming.

### PR DESCRIPTION
**Pull request by airalcorn2**

### CODE REVIEW

**Comment by emeryberger** [comment]
I will gladly take a PR to add the whole faculty of Univ of Wyoming, but not one for a single professor.

**Comment by airalcorn2** [comment]
You should probably clarify that requirement in the README.

**Comment by emeryberger** [comment]
Well, it's a ranking of departments, not people.

**Comment by airalcorn2** [comment]
Indeed, but that doesn't change the fact that the README doesn't seem to adequately describe the requirements for adding faculty. Best of luck with the project.

**Comment by emeryberger** [comment]
In nearly every case, PRs have been for institutions that are already in the database or adding whole departments; I have had very, very few submissions of individuals, so it's not a FAQ. But if you have some suggested wording for the README, I'd be happy to incorporate it.

**Pull request closed without merging**
