### PR TITLE
Robotics faculty at UofT

### PR DESCRIPTION
**Pull request by animesh-garg**
Animesh Garg,University of Toronto,http://www.cs.toronto.edu/~garg/,zp8V7ZMAAAAJ
Florian Shkurti,University of Toronto,http://www.cs.toronto.edu/~florian/,BDmtLHsAAAAJ
Jessica Burgner-Kahrs,University of Toronto,https://www.cs.toronto.edu/~jbk/,JtHZL24AAAAJ
Tim Barfoot,University of Toronto, http://asrl.utias.utoronto.ca/~tdb/,N_vPIhoAAAAJ
Raquel Urtasun,University of Toronto,http://www.cs.toronto.edu/~urtasun/,jyxO2akAAAAJ

Webpage for department faculty listing
http://web.cs.toronto.edu/people/faculty.htm

Note: Raquel is actively accepting students and doing departmental duties at UofT. 

# Contributing to CSrankings

Thanks for contributing to CSrankings! Here are some guidelines to getting your pull request accepted.

**Inclusion criteria**

- [x] Make sure that any faculty you add meet the inclusion
criteria. Eligible faculty include only full-time, tenure-track
faculty members on a given campus who can *solely* advise PhD students in
Computer Science. Faculty not in a CS department or similar who can
advise PhD students in CS can be included regardless of their home
department.

**Updating an affiliation or home page**

- [x] Update affiliations, home pages, and Google Scholar entries by modifying `csrankings.csv`. For the Google Scholar entry, just use the alphanumeric identifier in the middle of the URL. If none is there, put NOSCHOLARPAGE.

**Adding one or more faculty members (including an entire department)**

- [ ] If the department is not yet listed in CSrankings, the entire faculty needs to be added (not just one faculty member).

- [x] Enter each faculty member's [DBLP](http://dblp.org) name, home page, and Google Scholar entry (just the alphanumeric identifier, not the whole URL) by modifying `csrankings.csv`; include disambiguation suffixes like 0001 as needed. If the faculty entry is currently ambiguous, please do not include them. Send mail to the DBLP maintainers (dblp@dagstuhl.de) with a few publications by a particular faculty member; also, open an issue so that when the DBLP database is updated, that faculty member's information can be added.

- [ ] If DBLP has multiple entries for this person, all of them need to be listed. If an alias is not already present in `dblp-aliases.csv`, add it.

- [x] If the institution you are adding is not in the US,
update `country-info.csv`.

### CODE REVIEW

**Comment by emeryberger** [comment]
Part-time appointments explicitly do not meet the inclusion criteria. Please read over and check the appropriate boxes.

**Comment by animesh-garg** [comment]
So Raquel would not qualify to be counted?
checked the correct boxes now.

**Comment by emeryberger** [comment]
Correct, Raquel would not qualify unless she has a _full-time_ appointment, which seems incompatible with her current role.

**Comment by emeryberger** [comment]
Please update your PR with this deletion - thanks.

**Comment by animesh-garg** [comment]
removed Raquel. 
@emeryberger Could we update now. 
Thanks

**Comment by animesh-garg** [comment]
A kind reminder for merge @emeryberger

**Comment by animesh-garg** [comment]
bumping up for a merge. 
@emeryberger let me know if there is a change needed.

**Comment by animesh-garg** [comment]
Hi @emeryberger 
We would love for the site to be updated before the application season. 
Let me know if you don't find this to be correct or need something else. 
best

**Comment by animesh-garg** [comment]
Thanks!

**Pull request merged**
